### ISSUE TITLE
Error numba.cuda.cudadrv.error.NvvmError: Failed to compile, while testing SECOND model with pre-trained model and Config file

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/OpenPCDet#1016]
I am trying to test the SECOND model with pretrained model and config file, but when i run the test.py script i am getting the below error. I will appreciate if can get help with it .
```
2022-06-27 14:28:25,122   INFO  cfg.EXP_GROUP_PATH: workspace/OpenPCDet/tools/cfgs/kitti_models
2022-06-27 14:28:25,123   INFO  Loading KITTI dataset
2022-06-27 14:28:25,279   INFO  Total samples for KITTI dataset: 3769
2022-06-27 14:28:26,408   INFO  ==> Loading parameters from checkpoint /workspace/working_dir/second_7862.pth to GPU
2022-06-27 14:28:26,427   INFO  ==> Done (loaded 163/163)
2022-06-27 14:28:26,436   INFO  *************** EPOCH 7862 EVALUATION *****************
eval: 100%|████████████████████████████| 943/943 [00:59<00:00, 15.97it/s, recall_0.3=(0, 16665) / 17558]
2022-06-27 14:29:25,499   INFO  *************** Performance of EPOCH 7862 *****************
2022-06-27 14:29:25,499   INFO  Generate label finished(sec_per_example: 0.0157 second).
2022-06-27 14:29:25,499   INFO  recall_roi_0.3: 0.000000
2022-06-27 14:29:25,499   INFO  recall_rcnn_0.3: 0.949140
2022-06-27 14:29:25,499   INFO  recall_roi_0.5: 0.000000
2022-06-27 14:29:25,499   INFO  recall_rcnn_0.5: 0.891047
2022-06-27 14:29:25,499   INFO  recall_roi_0.7: 0.000000
2022-06-27 14:29:25,500   INFO  recall_rcnn_0.7: 0.665053
2022-06-27 14:29:25,502   INFO  Average predicted number of objects(3769 samples): 14.227
Traceback (most recent call last):
  File "/workspace/OpenPCDet/tools/test.py", line 200, in <module>
    main()
  File "/workspace/OpenPCDet/tools/test.py", line 196, in main
    eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test)
  File "/workspace/OpenPCDet/tools/test.py", line 62, in eval_single_ckpt
    eval_utils.eval_one_epoch(
  File "/workspace/OpenPCDet/tools/eval_utils/eval_utils.py", line 110, in eval_one_epoch
    result_str, result_dict = dataset.evaluation(
  File "/workspace/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 357, in evaluation
    from .kitti_object_eval_python import eval as kitti_eval
  File "/workspace/OpenPCDet/pcdet/datasets/kitti/kitti_object_eval_python/eval.py", line 6, in <module>
    from .rotate_iou import rotate_iou_gpu_eval
  File "/workspace/OpenPCDet/pcdet/datasets/kitti/kitti_object_eval_python/rotate_iou.py", line 263, in <module>
    def rotate_iou_kernel_eval(N, K, dev_boxes, dev_query_boxes, dev_iou, criterion=-1):
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/decorators.py", line 135, in kernel_jit
    return Dispatcher(func, sigs, bind=bind,
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 811, in __init__
    self.compile(sigs[0])
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 952, in compile
    kernel.bind()
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 576, in bind
    self._func.get()
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 446, in get
    ptx = self.ptx.get()
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 415, in get
    ptx = nvvm.llvm_to_ptx(self.llvmir, arch=arch,
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 548, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 236, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 254, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 144, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (91, 19): parse expected comma after load's type
NVVM_ERROR_COMPILATION
```

**Comment by XMing0124** [comment]
I encountered the same problem,do you fix it?

**Comment by ammaryasirnaich** [comment]
try to re-install numba with version=0.53.0 and check if it works

**Comment by mrprajesh** [comment]
@ammaryasirnaich On a different note, how did you collect the `development environment` details or which commands to use?
