### ISSUE TITLE
MPPNet waymo dataset cover have problem

### ISSUE THREAD

**Issue by xpyqiubai** [open-mmlab/OpenPCDet#1101]
when I use the sh
python -m pcdet.datasets.waymo.waymo_dataset --func create_waymo_gt_database --cfg_file tools/cfgs/dataset_configs/waymo_dataset_multiframe.yaml
for my old version add MPPNet support, will meet this issue
`
2022-09-13 13:07   warn(RuntimeWarning(msg))
2022-09-13 13:07 2022-09-13 05:07:33,692   INFO  Loading Waymo dataset
2022-09-13 13:07 2022-09-13 05:07:35,983   INFO  Total skipped info 0
2022-09-13 13:07 2022-09-13 05:07:35,983   INFO  Total samples for Waymo dataset: 39987
2022-09-13 13:07 2022-09-13 05:07:35,988   INFO  Loading Waymo dataset
2022-09-13 13:07 2022-09-13 05:07:49,089   INFO  Total skipped info 0
2022-09-13 13:07 2022-09-13 05:07:49,089   INFO  Total samples for Waymo dataset: 158081
2022-09-13 13:07 ---------------Start create groundtruth database for data augmentation---------------
2022-09-13 13:07 
  0%|          | 0/158081 [00:00<?, ?it/s]
  0%|          | 0/158081 [00:00<?, ?it/s]
2022-09-13 13:07 Traceback (most recent call last):
2022-09-13 13:07   File "/opt/conda/envs/opentwo/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2022-09-13 13:07     "__main__", mod_spec)
2022-09-13 13:07   File "/opt/conda/envs/opentwo/lib/python3.7/runpy.py", line 85, in _run_code
2022-09-13 13:07     exec(code, run_globals)
2022-09-13 13:07   File "/deeplearning/users/pengyuxie/code/claopenpcdet/OpenPCDet-master/pcdet/datasets/waymo/waymo_dataset.py", line 820, in <module>
2022-09-13 13:07     crop_gt_with_tail=not args.wo_crop_gt_with_tail
2022-09-13 13:07   File "/deeplearning/users/pengyuxie/code/claopenpcdet/OpenPCDet-master/pcdet/datasets/waymo/waymo_dataset.py", line 768, in create_waymo_gt_database
2022-09-13 13:07     used_classes=['Vehicle', 'Pedestrian', 'Cyclist'], processed_data_tag=processed_data_tag
2022-09-13 13:07   File "/deeplearning/users/pengyuxie/code/claopenpcdet/OpenPCDet-master/pcdet/datasets/waymo/waymo_dataset.py", line 494, in create_groundtruth_database
2022-09-13 13:07     info, points, sequence_name, sample_idx, self.dataset_cfg.SEQUENCE_CONFIG
2022-09-13 13:07 ValueError: too many values to unpack (expected 3)
`
how can I slove it?
Thank you very much.

**Comment by xpyqiubai** [comment]
Whether need change the line 494 to 
points, num_points_all, sample_idx_pre_list, poses, pred_boxes, pred_scores, pred_labels = self.get_sequence_data(
                    info, points, sequence_name, sample_idx, self.dataset_cfg.SEQUENCE_CONFIG
                )
This change is true?

**Comment by Cedarch** [comment]
Yes, your change is right. We will fix this bug soon.

**Comment by sshaoshuai** [comment]
Fixed in https://github.com/open-mmlab/OpenPCDet/pull/1103.
