### ISSUE TITLE
SyntaxError: invalid syntax，我的python版本是3.7，torch1.8.1+cu111 torchvision0.9.1+cu111 torchaudio==0.8.1，这个怎么解决阿

### ISSUE THREAD

**Issue by YJXTTZ** [open-mmlab/OpenPCDet#1110]
(openpcdet) zzp@zzp-pc:~/OpenPCDet/tools$ python demo.py --cfg_file ./cfgs/kitti_models/pointpillar_pyramid_aug.yaml --ckpt /home/juzhen/OpenPCDet/output/cfgs/kitti_models/pointpillar_pyramid_aug/default/ckpt/checkpoint_epoch_50.pth --data_path /home/juzhen/OpenPCDet/data/kitti/testing/velodyne/000008.bin
Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    from pcdet.datasets import DatasetTemplate
  File "/home/zzp/OpenPCDet/pcdet/datasets/__init__.py", line 8, in <module>
    from .dataset import DatasetTemplate
  File "/home/zzp/OpenPCDet/pcdet/datasets/dataset.py", line 8, in <module>
    from .augmentor.data_augmentor import DataAugmentor
  File "/home/zzp/OpenPCDet/pcdet/datasets/augmentor/data_augmentor.py", line 6, in <module>
    from . import augmentor_utils, database_sampler
  File "/home/zzp/OpenPCDet/pcdet/datasets/augmentor/database_sampler.py", line 6, in <module>
    from skimage import io
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/home/zzp/anaconda3/envs/openpcdet/lib/python3.7/site-packages/scikit_image-0.19.3-py3.7-linux-x86_64.egg/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/home/zzp/anaconda3/envs/openpcdet/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zzp/anaconda3/envs/openpcdet/lib/python3.7/site-packages/scikit_image-0.19.3-py3.7-linux-x86_64.egg/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/home/zzp/anaconda3/envs/openpcdet/lib/python3.7/site-packages/scikit_image-0.19.3-py3.7-linux-x86_64.egg/skimage/io/manage_plugins.py", line 23, in <module>
    from .collection import imread_collection_wrapper
  File "/home/zzp/anaconda3/envs/openpcdet/lib/python3.7/site-packages/scikit_image-0.19.3-py3.7-linux-x86_64.egg/skimage/io/collection.py", line 24, in <module>
    from tifffile import TiffFile
  File "/home/zzp/anaconda3/envs/openpcdet/lib/python3.7/site-packages/tifffile-2022.8.12-py3.7.egg/tifffile/__init__.py", line 3, in <module>
    from .tifffile import __doc__, __all__, __version__, main
  File "/home/zzp/anaconda3/envs/openpcdet/lib/python3.7/site-packages/tifffile-2022.8.12-py3.7.egg/tifffile/tifffile.py", line 1046
    /,
    ^
SyntaxError: invalid syntax

**Comment by YJXTTZ** [comment]
解决了，是为ubuntu20.04版本和python3.7版本对不上，换成python3.8就ok了
