### ISSUE TITLE
PillarNet test error

### ISSUE THREAD

**Issue by touristourist** [open-mmlab/OpenPCDet#1158]
Hi, I have a problem in PillarNet test stage. When I run command 
`python test.py --cfg_file cfgs/kitti_models/pillarnet_no_plane.yaml --batch_size 4 --ckpt ../output/kitti_models/pillarnet/default/ckpt/checkpoint_epoch_80.pth `, an error occurred like below. It seems during pillarne's post-processing, there is no key called 'final_box_dicts'. Since I‘m new to the point cloud, I don't know what causes the error. Looking forward to your reply! Thanks!

```
Traceback (most recent call last):
  File "/home/zhugezhengyang/anaconda3/envs/pcdet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhugezhengyang/anaconda3/envs/pcdet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/zhugezhengyang/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/data/zhugezhengyang/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/data/zhugezhengyang/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/data/zhugezhengyang/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/data/zhugezhengyang/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/data/zhugezhengyang/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/zhugezhengyang/zhugezhengyang/OpenPCDet/tools/test.py", line 207, in <module>
    main()
  File "/home/zhugezhengyang/zhugezhengyang/OpenPCDet/tools/test.py", line 203, in main
    eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test)
  File "/home/zhugezhengyang/zhugezhengyang/OpenPCDet/tools/test.py", line 65, in eval_single_ckpt
    eval_utils.eval_one_epoch(
  File "/home/zhugezhengyang/zhugezhengyang/OpenPCDet/tools/eval_utils/eval_utils.py", line 65, in eval_one_epoch
    pred_dicts, ret_dict = model(batch_dict)
  File "/home/zhugezhengyang/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/zhugezhengyang/zhugezhengyang/OpenPCDet/tools/../pcdet/models/detectors/pillarnet.py", line 21, in forward
    pred_dicts, recall_dicts = self.post_processing(batch_dict)
  File "/data/zhugezhengyang/zhugezhengyang/OpenPCDet/tools/../pcdet/models/detectors/pillarnet.py", line 39, in post_processing
    final_pred_dict = batch_dict['final_box_dicts']
KeyError: 'final_box_dicts'
```

**Comment by cat722** [comment]
@touristourist   Hello, I also encountered the same error, may I ask if you have solved it now？

**Comment by cat722** [comment]
![4VY)M)}%5BB1B9VTX~D)CXP](https://user-images.githubusercontent.com/58463987/198675978-35f26a4e-38ec-4fcc-92b7-d4880b3a04d4.png)

**Comment by cat722** [comment]
This my result, bach_size=8

**Comment by zhangkangkai** [comment]
> > @touristourist Hello, I also encountered the same error, may I ask if you have solved it now？
> 
> it seems that commenting out post_processing function in pillarnet.py works for me, but the following result on kitti is similar to that of PointPillar. What about your result on kitti?
> 
> ```
> Car AP@0.70, 0.70, 0.70:
> bbox AP:90.5350, 89.0212, 87.4191
> bev  AP:89.4004, 85.8414, 82.9450
> 3d   AP:85.5222, 76.1428, 72.0703
> aos  AP:90.51, 88.77, 87.06
> Car AP_R40@0.70, 0.70, 0.70:
> bbox AP:94.9326, 91.3999, 88.6204
> bev  AP:91.6973, 87.0841, 84.5465
> 3d   AP:86.9699, 76.6220, 72.8331
> aos  AP:94.90, 91.13, 88.25
> Car AP@0.70, 0.50, 0.50:
> bbox AP:90.5350, 89.0212, 87.4191
> bev  AP:90.6252, 89.6614, 88.8967
> 3d   AP:90.6075, 89.5458, 88.6373
> aos  AP:90.51, 88.77, 87.06
> Car AP_R40@0.70, 0.50, 0.50:
> bbox AP:94.9326, 91.3999, 88.6204
> bev  AP:95.2664, 94.0724, 93.0446
> 3d   AP:95.1990, 93.7418, 91.1931
> aos  AP:94.90, 91.13, 88.25
> Pedestrian AP@0.50, 0.50, 0.50:
> bbox AP:67.8565, 62.8025, 60.3019
> bev  AP:54.5556, 49.5916, 47.1515
> 3d   AP:48.4022, 43.5914, 39.9404
> aos  AP:58.08, 52.35, 49.65
> Pedestrian AP_R40@0.50, 0.50, 0.50:
> bbox AP:68.1989, 62.9536, 60.3299
> bev  AP:53.4131, 47.6099, 45.0900
> 3d   AP:45.9492, 41.0385, 37.4620
> aos  AP:58.10, 52.23, 49.49
> Pedestrian AP@0.50, 0.25, 0.25:
> bbox AP:67.8565, 62.8025, 60.3019
> bev  AP:74.4566, 69.8624, 67.3361
> 3d   AP:74.2832, 69.4694, 67.0166
> aos  AP:58.08, 52.35, 49.65
> Pedestrian AP_R40@0.50, 0.25, 0.25:
> bbox AP:68.1989, 62.9536, 60.3299
> bev  AP:75.2966, 70.4270, 67.4226
> 3d   AP:75.1109, 70.0331, 66.9968
> aos  AP:58.10, 52.23, 49.49
> Cyclist AP@0.50, 0.50, 0.50:
> bbox AP:84.6840, 70.3581, 67.4810
> bev  AP:81.0048, 63.4695, 59.5631
> 3d   AP:76.7292, 58.2300, 54.1787
> aos  AP:84.14, 68.77, 65.97
> Cyclist AP_R40@0.50, 0.50, 0.50:
> bbox AP:88.5217, 71.6948, 68.1102
> bev  AP:84.5284, 63.2617, 59.0671
> 3d   AP:78.5160, 57.6422, 53.5559
> aos  AP:87.87, 69.95, 66.39
> Cyclist AP@0.50, 0.25, 0.25:
> bbox AP:84.6840, 70.3581, 67.4810
> bev  AP:83.9366, 70.2489, 65.7101
> 3d   AP:83.9366, 70.2489, 65.7101
> aos  AP:84.14, 68.77, 65.97
> Cyclist AP_R40@0.50, 0.25, 0.25:
> bbox AP:88.5217, 71.6948, 68.1102
> bev  AP:87.7934, 70.5723, 66.1837
> 3d   AP:87.7934, 70.5723, 66.1837
> aos  AP:87.87, 69.95, 66.39
> ```

I have the same problem as you. Have you solved it? @touristourist

**Comment by iu110** [comment]
Hello, I also encountered the same error, may I ask if you have solved it now？
