### ISSUE TITLE
Error when I use demo.py to visualize result. How can I add images as input?

### ISSUE THREAD

**Issue by ChunZheng2022** [open-mmlab/OpenPCDet#1181]
Hello, error occured when I use demo.py to visualize my multimodal result. I want to know how can I read images in demo.py. Thank you very much.

2022-11-04 15:19:40,312 INFO ==> Loading parameters from checkpoint ../output/kitti_models/fspconv80.pth to CPU
2022-11-04 15:19:40,362 INFO ==> Checkpoint trained from version: pcdet+0.6.0+0000000
2022-11-04 15:19:40,411 INFO ==> Done (loaded 653/653)
2022-11-04 15:19:40,586 INFO Visualized sample index: 1
Traceback (most recent call last):
File "demo.py", line 112, in
main()
File "demo.py", line 98, in main
pred_dicts, _ = model.forward(data_dict)
File "/home/lcz/code/platform/openpcdet/pcdet/models/detectors/voxel_rcnn.py", line 11, in forward
batch_dict = cur_module(batch_dict)
File "/home/lcz/anaconda3/envs/cu113/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "/home/lcz/code/platform/openpcdet/pcdet/models/backbones_3d/spconv_backbone_focal.py", line 236, in forward
x_image = self.semseg(batch_dict['images'])['layer1_feat2d']
KeyError: 'images'

**Comment by meiyihTan** [comment]
I also facing the exactly same issue here, is there any idea to solve this?

**Comment by ChunZheng2022** [comment]
> I also facing the exactly same issue here, is there any idea to solve this?

Hi,
test.py is availabe for multimodal input. You can use test.py to get predict result and then visualize it yourself.
If using demo.py is required, I think you can try rewrite DemoDataset in demo.py.

**Comment by Mi97ch** [comment]
Do you mean that I can use test.py to detect objects on custom data?

**Comment by ChunZheng2022** [comment]
> Do you mean that I can use test.py to detect objects on custom data?

Yes, but you need to organize your data in kitti format
