### ISSUE TITLE
Fixing the compilation error of iou3d_nms on windows (on progress)

### ISSUE THREAD

**Issue by NLCharles** [open-mmlab/OpenPCDet#1287]
Hello, members of OpenPCDet,
I am working on the compilation error of the cuda ops in this repo on windows, and I have figured out the bugs.
Solution:
Step1: allocating memory like ```unsigned long long remv_cpu[col_blocks];``` is not allowed, and we use ```unsigned long long* remv_cpu = new unsigned long long[col_blocks];```. Remember to delete it before the function returns.
Step2: substitute ```unsigned long long``` with ```uint64_t``` and ``` long long``` with int64_t to solve symbolic linking error.
Should I set up a pull request to fix this?

**Comment by SE-Nickjackson** [comment]
Hi, I setup openPCDet on windows11. But when I try to train a pv-rcnn model with kitti dataset, I got some errors bellow:
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from test import repeat_eval_ckpt
  File "F:\OutSourcing\3d_object_detection\OpenPCDet\tools\test.py", line 14, in <module>
    from eval_utils import eval_utils
  File "F:\OutSourcing\3d_object_detection\OpenPCDet\tools\eval_utils\eval_utils.py", line 8, in <module>
    from pcdet.models import load_data_to_gpu
  File "..\pcdet\models\__init__.py", line 6, in <module>
    from .detectors import build_detector
  File "..\pcdet\models\detectors\__init__.py", line 1, in <module>
    from .detector3d_template import Detector3DTemplate
  File "..\pcdet\models\detectors\detector3d_template.py", line 6, in <module>
    from ...ops.iou3d_nms import iou3d_nms_utils
  File "..\pcdet\ops\iou3d_nms\iou3d_nms_utils.py", line 9, in <module>
    from ..iou3d_nms import iou3d_nms_cuda
ImportError: DLL load failed while importing iou3d_nms_cuda: The parameter is incorrect.
------------------------------
So, how can I solve this problem?
