### ISSUE TITLE
training error ONLY in Focals Conv 

### ISSUE THREAD

**Issue by Townjj** [open-mmlab/OpenPCDet#1301]
Hello, thanks for your excellent job!
But I meet the same training problem  **only in Focal conv** when using original version in delab-research/FocalsConv or in Openmmlab/OpenPCDet, and other models can train without any problem.
My env is ubuntu18.04 + Docker + RTX3090Ti *2 + Cuda11.3...
Can we find the problem and solve it together?  thanks.

```
#### training command #######
cd /PCDet2/FocalsConv/OpenPCDet/tools
python -m torch.distributed.launch --nproc_per_node=2 train.py --launcher pytorch \
--cfg_file /PCDet2/FocalsConv/OpenPCDet/tools/cfgs/kitti_models/voxel_rcnn_multiclasses_focalsconv.yaml
```

```
############ 
meet the same training problem **only in Focal conv ** when using original version in delab-research/FocalsConv or in Openmmlab/OpenPCDet, and other models can train without any problem.
############
2023-03-25 14:32:08,954   INFO  **********************Start training PCDet2/FocalsConv/OpenPCDet/tools/cfgs/kitti_models/voxel_rcnn_multiclasses_focalsconv(default)**********************
epochs:   0%|                                           | 0/80 [00:00<?, ?it/s../pcdet/models/backbones_3d/focal_sparse_conv/utils.py:25: UserWarning: volatile was removed (Variable.volatile is always False)
  mask = Variable(mask, volatile=index.volatile)
../pcdet/models/backbones_3d/focal_sparse_conv/utils.py:25: UserWarning: volatile was removed (Variable.volatile is always False)
  mask = Variable(mask, volatile=index.volatile)
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3458: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3458: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
Traceback (most recent call last):                                             
  File "train.py", line 201, in <module> [00:13<3:32:37, 13.76s/it, total_it=1]
    main()
  File "train.py", line 170, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/PCDet2/FocalsConv/OpenPCDet/tools/train_utils/train_utils.py", line 118, in train_model
    dataloader_iter=dataloader_iter
  File "/PCDet2/FocalsConv/OpenPCDet/tools/train_utils/train_utils.py", line 47, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "../pcdet/models/__init__.py", line 42, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/distributed.py", line 692, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
epochs:   0%| | 0/80 [00:35<?, ?it/s, loss=5.1, lr=0.001, d_time=1.16(1.16), f_
Traceback (most recent call last):
  File "train.py", line 201, in <module>
    main()
  File "train.py", line 170, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/PCDet2/FocalsConv/OpenPCDet/tools/train_utils/train_utils.py", line 118, in train_model
    dataloader_iter=dataloader_iter
  File "/PCDet2/FocalsConv/OpenPCDet/tools/train_utils/train_utils.py", line 47, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "../pcdet/models/__init__.py", line 42, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/distributed.py", line 692, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
                                                                              Killing subprocess 1721698                                                      
Killing subprocess 1721699
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'train.py', '--local_rank=1', '--launcher', 'pytorch', '--cfg_file', '/PCDet2/FocalsConv/OpenPCDet/tools/cfgs/kitti_models/voxel_rcnn_multiclasses_focalsconv.yaml']' returned non-zero exit status 1.
```

**Comment by yukang2017** [comment]
Hi,

I think this is a reduplicate issue to https://github.com/dvlab-research/FocalsConv/issues/28

It is solved and can be closed.


Regards,
Yukang Chen
