### ISSUE TITLE
Distributed training error

### ISSUE THREAD

**Issue by CBY-9527** [open-mmlab/OpenPCDet#1310]
Excuse me. I can train normally with a single card and multiple cards in the KITTI dataset. However, only a single card can be used for training on the waymo dataset, and an error will be reported when using multiple cards for training. Has anyone had a similar problem？ The error is as follows：

2023-04-04 11:50:35,273   INFO  **********************Start training waymo_models/pv_rcnn(default)*****************
epochs:   0%|                                                                                   | 0/30 [00:00<?, ?Killing subprocess 1914119
Killing subprocess 1914120
Killing subprocess 1914121
Killing subprocess 1914122
Traceback (most recent call last):
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, idule>
    main()
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, ikill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/media/vision/ycb/.conda/envs/pcdet1/bin/python', '-u', 'train.py', '--lrank=3', '--cfg_file', 'cfgs/waymo_models/pv_rcnn.yaml', '--launcher', 'pytorch']' died with <Signals.SIGKILL: 9>.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
(pcdet1) ycb@3090Server-4-3:~/1/OpenPCDet/tools$ /media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessinaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 18 leaked semaphores to clean up at shut
  len(cache))
/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphorcker: There appear to be 15 leaked semaphores to clean up at shutdown
  len(cache))
/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphorcker: There appear to be 15 leaked semaphores to clean up at shutdown
  len(cache))
/media/vision/ycb/.conda/envs/pcdet1/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphorcker: There appear to be 15 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by jetpackfirstme** [comment]
Hello, I also encountered the same question. How did you solve this?

**Comment by CBY-9527** [comment]
> 

I found that the process was killed because the CPU memory was too much and was not released. Distributed training on waymo requires a lot of CPU memory. Maybe you can check the CPU memory usage by typing （htop） in the terminal

**Comment by CBY-9527** [comment]
> 

I found that the process was killed because the CPU memory was too much and was not released. Distributed training on waymo requires a lot of CPU memory. Maybe you can check the CPU memory usage by typing （htop） in the terminal

**Comment by Petros626** [comment]
@CBY-9527 you mean the RAM?
