### ISSUE TITLE
ImportError: DLL load failed while importing iou3d_nms_cuda: The parameter is incorrect.

### ISSUE THREAD

**Issue by SE-Nickjackson** [open-mmlab/OpenPCDet#1314]
Hi, I setup openPCDet on windows11. But when I try to train a pv-rcnn model with kitti dataset, I got some errors bellow:
Traceback (most recent call last):
File "train.py", line 7, in
from test import repeat_eval_ckpt
File "F:\OutSourcing\3d_object_detection\OpenPCDet\tools\test.py", line 14, in
from eval_utils import eval_utils
File "F:\OutSourcing\3d_object_detection\OpenPCDet\tools\eval_utils\eval_utils.py", line 8, in
from pcdet.models import load_data_to_gpu
File "..\pcdet\models_init_.py", line 6, in
from .detectors import build_detector
File "..\pcdet\models\detectors_init_.py", line 1, in
from .detector3d_template import Detector3DTemplate
File "..\pcdet\models\detectors\detector3d_template.py", line 6, in
from ...ops.iou3d_nms import iou3d_nms_utils
File "..\pcdet\ops\iou3d_nms\iou3d_nms_utils.py", line 9, in
from ..iou3d_nms import iou3d_nms_cuda
ImportError: DLL load failed while importing iou3d_nms_cuda: The parameter is incorrect.
So, how can I solve this problem?

**Comment by yukang2017** [comment]
Hi, is the CUDA on your windows installed properly? I think this might be an environment issue.
