### ISSUE TITLE
Error using custom data while training

### ISSUE THREAD

**Issue by vishaldolase-honda** [open-mmlab/OpenPCDet#1376]
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main()
  File "train.py", line 175, in main
    train_model(
  File "/home/robot/OpenPCDet/tools/train_utils/train_utils.py", line 180, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/robot/OpenPCDet/tools/train_utils/train_utils.py", line 33, in train_one_epoch
    batch = next(dataloader_iter)
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/robot/.local/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/robot/OpenPCDet/tools/../pcdet/datasets/custom/custom_dataset.py", line 109, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/home/robot/OpenPCDet/tools/../pcdet/datasets/dataset.py", line 185, in prepare_data
    data_dict = self.data_augmentor.forward(
  File "/home/robot/OpenPCDet/tools/../pcdet/datasets/augmentor/data_augmentor.py", line 302, in forward
    data_dict = cur_augmentor(data_dict=data_dict)
  File "/home/robot/OpenPCDet/tools/../pcdet/datasets/augmentor/database_sampler.py", line 497, in __call__
    data_dict = self.add_sampled_boxes_to_scene(
  File "/home/robot/OpenPCDet/tools/../pcdet/datasets/augmentor/database_sampler.py", line 398, in add_sampled_boxes_to_scene
    obj_points = np.fromfile(str(file_path), dtype=np.float64).reshape(-1, self.sampler_cfg.NUM_POINT_FEATURES)
ValueError: cannot reshape array of size 246 into shape (4)

**Comment by vishaldolase-honda** [comment]
I am using a custom data, 
my pointcloud details(from labelcloud) are

Number of Points: 13441
Number of Colors: 13441
Point Cloud Center: [ 5.46 -0.05 -1.04]
Point Cloud Minimums: [ 0. -8.05 -2.02]
Point Cloud Maximums: [14.69 8.32 -0.08]
Initial Translation: [ -5.46 0.05 -21.04]

i have created labels according to [given](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/CUSTOM_DATASET_TUTORIAL.md#label-format) format

example 
6.4 -0.0 -1.25 0.85 0.75 1.35 -0.38  Pedestrian

currently i have only 1 class pedestrian

i made following changes in 
custom_dataset.yaml

POINT_CLOUD_RANGE: [0.0, -8.05, -2.02, 14.69, 8.32, -0.08]

MAP_CLASS_TO_KITTI: {
    'Pedestrian': 'Pedestrian',
}


POINT_FEATURE_ENCODING: {
    encoding_type: absolute_coordinates_encoding,
    used_feature_list: ['x', 'y', 'z', 'intensity'],
    src_feature_list: ['x', 'y', 'z', 'intensity'],
}


  PREPARE: {
     filter_by_min_points: ['Pedestrian:5'],
}

 SAMPLE_GROUPS: ['Pedestrian:15']
VOXEL_SIZE: [0.1, 0.1, 0.15]
    
    
  After making changes i ran
  python -m pcdet.datasets.custom.custom_dataset create_custom_infos tools/cfgs/dataset_configs/custom_dataset.yaml
  
now i want to implement PartA2_free model

so i made changes in PartA2_free.yaml

CLASS_NAMES: ['Robot']

DATA_CONFIG:
    _BASE_CONFIG_: cfgs/dataset_configs/custom_dataset.yaml  
    
 Finally im hitting 
 python3 train.py  --cfg_file /home/robot/OpenPCDet/tools/cfgs/kitti_models/PartA2_free.yaml 
 
 
 But i am getting error:

Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main()
  File "train.py", line 175, in main
    train_model(
  File "/home/robot/OpenPCDet/tools/train_utils/train_utils.py", line 180, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/robot/OpenPCDet/tools/train_utils/train_utils.py", line 33, in train_one_epoch
    batch = next(dataloader_iter)
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/robot/.local/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/robot/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/robot/OpenPCDet/tools/../pcdet/datasets/custom/custom_dataset.py", line 109, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/home/robot/OpenPCDet/tools/../pcdet/datasets/dataset.py", line 185, in prepare_data
    data_dict = self.data_augmentor.forward(
  File "/home/robot/OpenPCDet/tools/../pcdet/datasets/augmentor/data_augmentor.py", line 302, in forward
    data_dict = cur_augmentor(data_dict=data_dict)
  File "/home/robot/OpenPCDet/tools/../pcdet/datasets/augmentor/database_sampler.py", line 497, in __call__
    data_dict = self.add_sampled_boxes_to_scene(
  File "/home/robot/OpenPCDet/tools/../pcdet/datasets/augmentor/database_sampler.py", line 398, in add_sampled_boxes_to_scene
    obj_points = np.fromfile(str(file_path), dtype=np.float64).reshape(-1, self.sampler_cfg.NUM_POINT_FEATURES)
ValueError: cannot reshape array of size 246 into shape (4)


Now, is there something which i am missing can anyone help ?

**Comment by regenthor** [comment]
I'm having this problem too, can anyone solve it? @vishaldolase-honda

**Comment by vishaldolase-honda** [comment]
@regenthor 
Please make sure:

point cloud range along z-axis / voxel_size is 40
point cloud range along x,y -axis / voxel_size is the multiple of 16.

as mentioned in [here](https://github.com/open-mmlab/OpenPCDet/issues/253#issuecomment-679190936)
