### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by 751K** [open-mmlab/OpenPCDet#1401]
执行python setup.py develop时报错
环境：win下使用wsl2下的ubuntu进行编译，cu11.3，pytorch1.12，尝试更换cu和对应pytorch版本无效
具体信息：
[13/13] /usr/local/cuda-11.3/bin/nvcc  -I/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/include -I/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/includ
e/torch/csrc/api/include -I/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/include/TH -I/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/include/THC -I/us
r/local/cuda-11.3/include -I/home/k101/anaconda3/envs/cu113py310/include/python3.10 -c -c /mnt/e/code/python/OpenPCDet-master/pcdet/ops/pointnet2/pointnet2_stack/src/sampling_gpu.cu -o /mnt/e/code/pyth
on/OpenPCDet-master/build/temp.linux-x86_64-cpython-310/pcdet/ops/pointnet2/pointnet2_stack/src/sampling_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIO
NS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPY
BIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointnet2_stack_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointnet2_stack_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14     
/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/include/c10/core/SymInt.h(84): warning: integer conversion resulted in a change of sign

/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/include/c10/core/SymInt.h(84): warning: integer conversion resulted in a change of sign

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/e/code/python/OpenPCDet-master/setup.py", line 34, in <module>
    setup(
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/command/develop.py", line 115, in install_for_development
    self.run_command('build_ext')
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/k101/anaconda3/envs/cu113py310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by JonathanFK981** [comment]
You need to set the cuda environment variable to /usr/local/cuda-{version} instead of /usr/local/cuda

**Comment by stu-zhangxl** [comment]
me too!

**Comment by AmrinKareem** [comment]
@stu-zhangxl @751K @openmmlab-bot  I am facing the same error when running python setup.py develop. Has anyone solved this yet?

**Comment by XiangyPeng** [comment]
Same for me. Is there any clue?

**Comment by stu-zhangxl** [comment]
You can try this operation: python setup.py develop. @XiangyPeng 
At the same time, thank you also to @AmrinKareem  Based on your operation, I can run normally on my end.

**Comment by Li018** [comment]
> You can try this operation: python setup.py develop. @XiangyPeng At the same time, thank you also to @AmrinKareem Based on your operation, I can run normally on my end.
你是怎么解决的哇
