### ISSUE TITLE
When running python setup.py develop, I encountered an error. What could be the issue?

### ISSUE THREAD

**Issue by sgrrlll** [open-mmlab/OpenPCDet#1454]
I'm running it under an environment copied from another computer, and CUDA is already installed, and the nvcc -V command does not report any errors.Error message as follows：
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/7] :/home/shuxue3/.local/cuda-12.1/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_attention_indices_gpu.o.d -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_attention_indices_gpu.cu -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_attention_indices_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_attention_indices_gpu.o
:/home/shuxue3/.local/cuda-12.1/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_attention_indices_gpu.o.d -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_attention_indices_gpu.cu -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_attention_indices_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/bin/sh: 1: :/home/shuxue3/.local/cuda-12.1/bin/nvcc: not found
[2/7] :/home/shuxue3/.local/cuda-12.1/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_mapping_gpu.o.d -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_mapping_gpu.cu -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_mapping_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_mapping_gpu.o
:/home/shuxue3/.local/cuda-12.1/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_mapping_gpu.o.d -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_mapping_gpu.cu -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_mapping_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/bin/sh: 1: :/home/shuxue3/.local/cuda-12.1/bin/nvcc: not found
[3/7] :/home/shuxue3/.local/cuda-12.1/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/group_features_gpu.o.d -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/group_features_gpu.cu -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/group_features_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/group_features_gpu.o
:/home/shuxue3/.local/cuda-12.1/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/group_features_gpu.o.d -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/group_features_gpu.cu -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/group_features_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/bin/sh: 1: :/home/shuxue3/.local/cuda-12.1/bin/nvcc: not found
[4/7] c++ -MMD -MF /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_attention_indices.o.d -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_attention_indices.cpp -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_attention_indices.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_attention_indices.o
c++ -MMD -MF /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_attention_indices.o.d -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_attention_indices.cpp -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_attention_indices.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC/THCGeneral.h:7,
                 from /home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC/THC.h:4,
                 from /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_attention_indices.cpp:8:
/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: 没有那个文件或目录
    6 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[5/7] c++ -MMD -MF /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/group_features.o.d -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/group_features.cpp -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/group_features.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/group_features.o
c++ -MMD -MF /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/group_features.o.d -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/group_features.cpp -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/group_features.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/group_features.cpp:9:10: fatal error: cuda.h: 没有那个文件或目录
    9 | #include <cuda.h>
      |          ^~~~~~~~
compilation terminated.
[6/7] c++ -MMD -MF /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_mapping.o.d -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_mapping.cpp -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_mapping.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_mapping.o
c++ -MMD -MF /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_mapping.o.d -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_mapping.cpp -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/build_mapping.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC/THCGeneral.h:7,
                 from /home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC/THC.h:4,
                 from /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_mapping.cpp:8:
/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: 没有那个文件或目录
    6 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[7/7] c++ -MMD -MF /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/votr_api.o.d -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/votr_api.cpp -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/votr_api.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/votr_api.o
c++ -MMD -MF /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/votr_api.o.d -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/TH -I/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/THC -I:/home/shuxue3/.local/cuda-12.1/include -I/home/shuxue3/anaconda3/envs/casa/include/python3.8 -c -c /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/votr_api.cpp -o /home/shuxue3/lyk/CaSA-3DHANet/build/temp.linux-x86_64-cpython-38/pcdet/ops/votr_ops/src/votr_api.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=votr_ops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:140,
                 from /home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                 from /home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/votr_api.cpp:2:
/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:83: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
   83 | #pragma omp parallel for if ((end - begin) >= grain_size)
      |
In file included from /home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/votr_api.cpp:4:
/home/shuxue3/lyk/CaSA-3DHANet/pcdet/ops/votr_ops/src/build_mapping_gpu.h:11:10: fatal error: cuda.h: 没有那个文件或目录
   11 | #include <cuda.h>
      |          ^~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    setup(
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
    self.run_command('build_ext')
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/shuxue3/anaconda3/envs/casa/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by SinaDavari** [comment]
Same error here... Any solutions?

**Comment by kbratsy** [comment]
I also encounter the same error while compiling. I would appreciate it if you could provide any guidance.

**Comment by sgrrlll** [comment]
> Same error here... Any solutions?

The CUDA version is not right, I lowered the version and it was fine

**Comment by sgrrlll** [comment]
> I also encounter the same error while compiling. I would appreciate it if you could provide any guidance.

The CUDA version is not right, I lowered the version and it was fine
