### ISSUE TITLE
SOS 🥇 Question about "No module named 'pcdet.datasets.argo2.argo2_utils' " when launch a demo.py

### ISSUE THREAD

**Issue by thiesymon** [open-mmlab/OpenPCDet#1486]
I have run  python setup.py develop with successfule result:Finished processing dependencies for pcdet==0.6.0+255db8f
 when I run a demo in directory OpenPCDet/tools: python demo.py --cfg_file cfgs/kitti_models/pointpillar.yaml  --ckpt pointpillar_7728.pth  --data_path ~/nets/OpenPCDet/data/kitti/training/velodyne/000008.bin
 I shows :

```
Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    from pcdet.datasets import DatasetTemplate
  File "/home/thiesy/miniconda3/envs/openpcdet/lib/python3.8/site-packages/pcdet-0.6.0+255db8f-py3.8-linux-x86_64.egg/pcdet/datasets/__init__.py", line 15, in <module>
    from .argo2.argo2_dataset import Argo2Dataset
  File "/home/thiesy/miniconda3/envs/openpcdet/lib/python3.8/site-packages/pcdet-0.6.0+255db8f-py3.8-linux-x86_64.egg/pcdet/datasets/argo2/argo2_dataset.py", line 15, in <module>
    from .argo2_utils.so3 import yaw_to_quat, quat_to_yaw
ModuleNotFoundError: No module named 'pcdet.datasets.argo2.argo2_utils'
```

 who can help with above ???

**Comment by Zixiu99** [comment]
Have you solved the problem? I had the same problem.

**Comment by Zixiu99** [comment]
I've had that problem. To resolve the issue, replace the pcdet folder in/home/thiesy/miniconda3/envs/openpcdet/lib/python3.8/site-packages/pcdet-0.6.0+255db8f-py3.8-linux-x86_64.egg/pcdet with the pcdet folder from the project.

**Comment by hitbuyi** [comment]
I have thesame problem when I install pcdet as *.whl file
