### ISSUE TITLE
Issue about import pcdet.datasets.kitti.kitti_dataset

### ISSUE THREAD

**Issue by vincezh2000** [open-mmlab/OpenPCDet#1560]
when trying to import kitti, it shows that RuntimeError: 
cannot statically infer the expected size of a list in this context: :

Traceback (most recent call last):
  File "/home/tz2693/LCDNet/pcdet_test.py", line 1, in <module>
    from pcdet.datasets.kitti.kitti_dataset import KittiDataset
  File "/home/tz2693/LCDNet/OpenPCDet/pcdet/datasets/__init__.py", line 15, in <module>
    from .argo2.argo2_dataset import Argo2Dataset
  File "/home/tz2693/LCDNet/OpenPCDet/pcdet/datasets/argo2/argo2_dataset.py", line 15, in <module>
    from .argo2_utils.so3 import yaw_to_quat, quat_to_yaw
  File "/home/tz2693/LCDNet/OpenPCDet/pcdet/datasets/argo2/argo2_utils/so3.py", line 10, in <module>
    def quat_to_mat(quat_wxyz: Tensor) -> Tensor:
  File "/home/tz2693/miniconda3/envs/l/lib/python3.8/site-packages/torch/jit/_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
  File "/home/tz2693/miniconda3/envs/l/lib/python3.8/site-packages/torch/jit/_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "/home/tz2693/miniconda3/envs/l/lib/python3.8/site-packages/torch/jit/_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 
cannot statically infer the expected size of a list in this context:
  File "/home/tz2693/miniconda3/envs/l/lib/python3.8/site-packages/kornia/geometry/conversions.py", line 556

    # this slightly awkward construction of the output shape is to satisfy torchscript
    output_shape = [*list(quaternion.shape[:-1]), 3, 3]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    matrix = matrix_flat.reshape(output_shape)
'quaternion_to_rotation_matrix' is being compiled since it was called from 'quat_to_mat'
  File "/home/tz2693/LCDNet/OpenPCDet/pcdet/datasets/argo2/argo2_utils/so3.py", line 19
        (...,3,3) 3D rotation matrices.
    """
    return C.quaternion_to_rotation_matrix(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        quat_wxyz, order=C.QuaternionCoeffOrder.WXYZ
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    )


Process finished with exit code 1

**Comment by kosmastsk** [comment]
Probably same issue as #1487
