### ISSUE TITLE
something wrong when preprocess waymodataset.  tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory

### ISSUE THREAD

**Issue by RhythmOfTheRain-Byte** [open-mmlab/OpenPCDet#1572]
Excuse me. When i run python -m pcdet.datasets.waymo.waymo_dataset --func create_waymo_infos --cfg_file tools/cfgs/dataset_configs/waymo_dataset.yaml.  Something went wrong.
Does anyone know how to solve the problem as blow.

Traceback (most recent call last):
File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
r = call_item.fn(*call_item.args, **call_item.kwargs)
File "/usr/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
return [fn(*args) for args in chunk]
File "/usr/lib/python3.8/concurrent/futures/process.py", line 198, in
return [fn(*args) for args in chunk]
File "/home/mlcnet/pcdet/datasets/waymo/waymo_utils.py", line 196, in process_single_sequence
dataset = tf.data.TFRecordDataset(str(sequence_file), compression_type='')
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/readers.py", line 336, in init
filenames = _create_or_validate_filenames_dataset(filenames)
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/readers.py", line 56, in _create_or_validate_filenames_dataset
filenames = ops.convert_to_tensor(filenames, dtype_hint=dtypes.string)
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 1328, in convert_to_tensor
ret = conversion_func(
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py", line 321, in _constant_tensor_conversion_function
return constant(v, dtype=dtype, name=name)
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py", line 261, in constant
return _constant_impl(value, dtype, shape, name, verify_shape=False,
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py", line 270, in _constant_impl
t = convert_to_eager_tensor(value, ctx, dtype)
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py", line 95, in convert_to_eager_tensor
ctx.ensure_initialized()
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/context.py", line 515, in ensure_initialized
context_handle = pywrap_tfe.TFE_NewContext(opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/mlcnet/pcdet/datasets/waymo/waymo_dataset.py", line 416, in
create_waymo_infos(
File "/home/mlcnet/pcdet/datasets/waymo/waymo_dataset.py", line 375, in create_waymo_infos
waymo_infos_train = dataset.get_infos(
File "/home/mlcnet/pcdet/datasets/waymo/waymo_dataset.py", line 113, in get_infos
sequence_infos = list(tqdm(executor.map(process_single_sequence, sample_sequence_file_list),
File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1129, in iter
for obj in iterable:
File "/usr/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
for element in iterable:
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
yield fs.pop().result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
return self.__get_result()
File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
raise self._exception
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory

**Comment by sweunwave** [comment]
Hello, 
I'm also dealing with the same problem as you.

Did you solve this problem?

Thank you.
