### ISSUE TITLE
ValueError: Cannot take a larger sample than population when 'replace=False'

### ISSUE THREAD

**Issue by MartinHahner** [open-mmlab/OpenPCDet#313]
```bash
2020-10-10 19:21:04,495   INFO  **********************start of training**********************
epochs:   0%|          | 0/80 [00:54<?, ?it/s]
Traceback (most recent call last):00<?, ?it/s]
  File "train.py", line 239, in <module>
    main()
  File "train.py", line 214, in main
    wandb_run=run)
  File "/home/ubuntu/efs/tmp_git/2020-10-10_21-16-23_efb07ac/tools/train_utils/train_utils.py", line 112, in train_model
    wandb_run=wandb_run)
  File "/home/ubuntu/efs/tmp_git/2020-10-10_21-16-23_efb07ac/tools/train_utils/train_utils.py", line 24, in train_one_epoch
    batch = next(dataloader_iter)
  File "/home/ubuntu/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/ubuntu/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/efs/tmp_git/2020-10-10_21-16-23_efb07ac/pcdet/datasets/dense/dense_dataset.py", line 466, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/home/ubuntu/efs/tmp_git/2020-10-10_21-16-23_efb07ac/pcdet/datasets/dataset.py", line 142, in prepare_data
    data_dict=data_dict
  File "/home/ubuntu/efs/tmp_git/2020-10-10_21-16-23_efb07ac/pcdet/datasets/processor/data_processor.py", line 123, in forward
    data_dict = cur_processor(data_dict=data_dict)
  File "/home/ubuntu/efs/tmp_git/2020-10-10_21-16-23_efb07ac/pcdet/datasets/processor/data_processor.py", line 104, in sample_points
    extra_choice = np.random.choice(choice, num_points - len(points), replace=False)
  File "mtrand.pyx", line 954, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
```

**Comment by MartinHahner** [comment]
I think it has nothing to do with batch_size actually, but with my "custom" sparse scenes.
`num_points - len(points) = 11.786`
`len(choice) = 4598`

Trying to fix it by
```python
            choice = np.arange(0, len(points), dtype=np.int32)
            if num_points > len(points):
                while (num_points - len(points)) > len(choice):
                    choice = np.concatenate((choice, choice), axis=0)
                extra_choice = np.random.choice(choice, num_points - len(points), replace=False)
                choice = np.concatenate((choice, extra_choice), axis=0)
            np.random.shuffle(choice)
```
leads to an error at https://github.com/open-mmlab/OpenPCDet/blob/f982b5bfdf0e8e15a2e2d7fead2925ff564051d7/pcdet/models/backbones_3d/pointnet2_backbone.py#L76

```bash
epochs:   0%|          | 0/80 [02:38<?, ?it/s]
Traceback (most recent call last):
  File "/home/martin/repositories/PCDet/tools/train_utils/train_utils.py", line 112, in train_model
    wandb_run=wandb_run)
  File "/home/martin/repositories/PCDet/tools/train_utils/train_utils.py", line 45, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/home/martin/repositories/PCDet/pcdet/models/__init__.py", line 31, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/martin/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/martin/repositories/PCDet/pcdet/models/detectors/point_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/martin/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/martin/repositories/PCDet/pcdet/models/backbones_3d/pointnet2_backbone.py", line 76, in forward
    assert xyz_batch_cnt.min() == xyz_batch_cnt.max(), f'{xyz_batch_cnt.min()} != {xyz_batch_cnt.max()}'
AssertionError: 22026 != 30178
```
@sshaoshuai: any suggestions?

**Comment by MartinHahner** [comment]
fixed it [here](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/processor/data_processor.py#L102-L106):
```python
            choice = np.arange(0, len(points), dtype=np.int32)
            if num_points > len(points):
                duplicates = None
                diff = num_points - len(points)
                while diff > len(choice):
                    diff -= len(choice)
                    if duplicates is None:
                        duplicates = choice
                    else:
                        duplicates = np.concatenate((duplicates, duplicates), axis=0)
                extra_choice = np.random.choice(choice, diff, replace=False)
                choice = np.concatenate((choice, duplicates), axis=0)
                choice = np.concatenate((choice, extra_choice), axis=0)
            np.random.shuffle(choice)
```
