### ISSUE TITLE
Error when I run "python demo.py --cfg_file cfgs/nuscenes_models/cbgs_pp_multihead.yaml --ckpt pp_multihead_nds5823_updated.pth --data_path 4dc98064647f400bb2e797f95e4500cb_lidarseg.bin"

### ISSUE THREAD

**Issue by kirima-h** [open-mmlab/OpenPCDet#317]
2020-10-15 10:35:12,777   INFO  -----------------Quick Demo of OpenPCDet-------------------------
2020-10-15 10:35:12,777   INFO  Total number of samples: 	1
2020-10-15 10:35:15,051   INFO  ==> Loading parameters from checkpoint pp_multihead_nds5823_updated.pth to CPU
2020-10-15 10:35:15,779   INFO  ==> Done (loaded 421/421)
2020-10-15 10:35:15,794   INFO  Visualized sample index: 	1
Traceback (most recent call last):
  File "demo.py", line 103, in <module>
    main()
  File "demo.py", line 91, in main
    pred_dicts, _ = model.forward(data_dict)
  File "/home/kirima/Documents/OpenPCDet/pcdet/models/detectors/pointpillar.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/kirima/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirima/Documents/OpenPCDet/pcdet/models/backbones_3d/vfe/pillar_vfe.py", line 120, in forward
    features = pfn(features)
  File "/home/kirima/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirima/Documents/OpenPCDet/pcdet/models/backbones_3d/vfe/pillar_vfe.py", line 37, in forward
    x = self.linear(inputs)
  File "/home/kirima/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirima/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/kirima/anaconda3/envs/PCDet/lib/python3.6/site-packages/torch/nn/functional.py", line 1371, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [20 x 10], m2: [11 x 64] at /opt/conda/conda-bld/pytorch_1565287148058/work/aten/src/THC/generic/THCTensorMathBlas.cu:273

I download mini nusences date and test in demo, error occurred.thanks for your help.

**Comment by sshaoshuai** [comment]
Please refer to https://github.com/open-mmlab/OpenPCDet/issues/195.
