### ISSUE TITLE
PVRCNN with KITTI data when run train.py cause initialization error  

### ISSUE THREAD

**Issue by AAArielo** [open-mmlab/OpenPCDet#367]
First,thank you for all contributions, the following are the problems I encountered

when I run this command python train.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml 
I don't know why cause this error, both pv_rcnn.yaml and PartA2.yaml have the same problem
but training pointrcnn.yaml is successful.
I would be very grateful if you could answer.

Traceback (most recent call last):                                                                                                                                                                                  | 0/1238 [00:00<?, ?it/s]
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 170, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/home/awinlab/Documents/AAArielo/OpenPCDet-master/tools/train_utils/train_utils.py", line 93, in train_model
    dataloader_iter=dataloader_iter
  File "/home/awinlab/Documents/AAArielo/OpenPCDet-master/tools/train_utils/train_utils.py", line 38, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/home/awinlab/Documents/AAArielo/OpenPCDet-master/pcdet/models/__init__.py", line 30, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/awinlab/anaconda3/envs/aaarielo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/awinlab/Documents/AAArielo/OpenPCDet-master/pcdet/models/detectors/pv_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/awinlab/anaconda3/envs/aaarielo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/awinlab/Documents/AAArielo/OpenPCDet-master/pcdet/models/backbones_3d/spconv_backbone.py", line 139, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/awinlab/anaconda3/envs/aaarielo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/awinlab/anaconda3/envs/aaarielo/lib/python3.7/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/home/awinlab/anaconda3/envs/aaarielo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/awinlab/anaconda3/envs/aaarielo/lib/python3.7/site-packages/spconv/conv.py", line 181, in forward
    use_hash=self.use_hash)
  File "/home/awinlab/anaconda3/envs/aaarielo/lib/python3.7/site-packages/spconv/ops.py", line 95, in get_indice_pairs
    int(use_hash))
RuntimeError: /home/awinlab/Documents/AAArielo/spconv/src/spconv/indice.cu 274
cuda execution failed with error 3 initialization error
prepareSubMGridKernel failed

codatoolkit 10.2
pytorch 1.7
spconv 1.2

**Comment by sshaoshuai** [comment]
I never saw this problem before, and it seems like a problem of spconv. 
I also notice this issue https://github.com/open-mmlab/OpenPCDet/issues/338, both of you use pytorch 1.7 with spconv 1.2. 
Maybe you could try to use pytorch 1.6 with spconv 1.2, and I have sucessfully trained with this envoriment before.
