### ISSUE TITLE
ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by TianchaoHuo** [open-mmlab/OpenPCDet#504]
Platform: 
Ubuntu16.04 
pytorch=1.3.1
cuda=10.0

hello, while trying to train the pointpillars network using custom kitti-like dataset, I encounter a problem :

2021-04-14 10:41:50,502   INFO  **********************Start logging**********************
2021-04-14 10:41:50,502   INFO  CUDA_VISIBLE_DEVICES=ALL
2021-04-14 10:41:50,502   INFO  cfg_file         ./cfgs/kitti_models/car_kitti_pp.yaml
2021-04-14 10:41:50,503   INFO  batch_size       4
2021-04-14 10:41:50,503   INFO  epochs           80
2021-04-14 10:41:50,503   INFO  workers          8
2021-04-14 10:41:50,503   INFO  extra_tag        default
2021-04-14 10:41:50,503   INFO  ckpt             None
2021-04-14 10:41:50,503   INFO  pretrained_model None
2021-04-14 10:41:50,503   INFO  launcher         none
2021-04-14 10:41:50,503   INFO  tcp_port         18888
2021-04-14 10:41:50,503   INFO  sync_bn          False
2021-04-14 10:41:50,503   INFO  fix_random_seed  False
2021-04-14 10:41:50,503   INFO  ckpt_save_interval 1
2021-04-14 10:41:50,503   INFO  local_rank       0
2021-04-14 10:41:50,503   INFO  max_ckpt_save_num 30
2021-04-14 10:41:50,503   INFO  merge_all_iters_to_one_epoch False
2021-04-14 10:41:50,503   INFO  set_cfgs         None
2021-04-14 10:41:50,503   INFO  max_waiting_mins 0
2021-04-14 10:41:50,503   INFO  start_epoch      0
2021-04-14 10:41:50,503   INFO  save_to_file     False
2021-04-14 10:41:50,503   INFO  cfg.ROOT_DIR: /home/wu/OpenPCDet
2021-04-14 10:41:50,503   INFO  cfg.LOCAL_RANK: 0
2021-04-14 10:41:50,503   INFO  cfg.CLASS_NAMES: ['Car']
2021-04-14 10:41:50,503   INFO  
cfg.DATA_CONFIG = edict()
2021-04-14 10:41:50,503   INFO  cfg.DATA_CONFIG.DATASET: KittiDataset
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.DATA_PATH: ../data/kitti
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.POINT_CLOUD_RANGE: [0, -39.68, -3, 69.12, 39.68, 1]
2021-04-14 10:41:50,504   INFO  
cfg.DATA_CONFIG.DATA_SPLIT = edict()
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.DATA_SPLIT.train: train
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.DATA_SPLIT.test: val
2021-04-14 10:41:50,504   INFO  
cfg.DATA_CONFIG.INFO_PATH = edict()
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.INFO_PATH.train: ['kitti_infos_train.pkl']
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.INFO_PATH.test: ['kitti_infos_val.pkl']
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.FOV_POINTS_ONLY: True
2021-04-14 10:41:50,504   INFO  
cfg.DATA_CONFIG.DATA_AUGMENTOR = edict()
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.DATA_AUGMENTOR.DISABLE_AUG_LIST: ['placeholder']
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.DATA_AUGMENTOR.AUG_CONFIG_LIST: [{'NAME': 'gt_sampling', 'USE_ROAD_PLANE': True, 'DB_INFO_PATH': ['kitti_dbinfos_train.pkl'], 'PREPARE': {'filter_by_min_points': ['Car:5'], 'filter_by_difficulty': [-1]}, 'SAMPLE_GROUPS': ['Car:15'], 'NUM_POINT_FEATURES': 4, 'DATABASE_WITH_FAKELIDAR': False, 'REMOVE_EXTRA_WIDTH': [0.0, 0.0, 0.0], 'LIMIT_WHOLE_SCENE': False}, {'NAME': 'random_world_flip', 'ALONG_AXIS_LIST': ['x']}, {'NAME': 'random_world_rotation', 'WORLD_ROT_ANGLE': [-0.78539816, 0.78539816]}, {'NAME': 'random_world_scaling', 'WORLD_SCALE_RANGE': [0.95, 1.05]}]
2021-04-14 10:41:50,504   INFO  
cfg.DATA_CONFIG.POINT_FEATURE_ENCODING = edict()
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.POINT_FEATURE_ENCODING.encoding_type: absolute_coordinates_encoding
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.POINT_FEATURE_ENCODING.used_feature_list: ['x', 'y', 'z', 'intensity']
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.POINT_FEATURE_ENCODING.src_feature_list: ['x', 'y', 'z', 'intensity']
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG.DATA_PROCESSOR: [{'NAME': 'mask_points_and_boxes_outside_range', 'REMOVE_OUTSIDE_BOXES': True}, {'NAME': 'shuffle_points', 'SHUFFLE_ENABLED': {'train': True, 'test': False}}, {'NAME': 'transform_points_to_voxels', 'VOXEL_SIZE': [0.16, 0.16, 4], 'MAX_POINTS_PER_VOXEL': 32, 'MAX_NUMBER_OF_VOXELS': {'train': 16000, 'test': 40000}}]
2021-04-14 10:41:50,504   INFO  cfg.DATA_CONFIG._BASE_CONFIG_: cfgs/dataset_configs/kitti_dataset.yaml
2021-04-14 10:41:50,504   INFO  
cfg.MODEL = edict()
2021-04-14 10:41:50,504   INFO  cfg.MODEL.NAME: PointPillar
2021-04-14 10:41:50,504   INFO  
cfg.MODEL.VFE = edict()
2021-04-14 10:41:50,504   INFO  cfg.MODEL.VFE.NAME: PillarVFE
2021-04-14 10:41:50,504   INFO  cfg.MODEL.VFE.WITH_DISTANCE: False
2021-04-14 10:41:50,505   INFO  cfg.MODEL.VFE.USE_ABSLOTE_XYZ: True
2021-04-14 10:41:50,505   INFO  cfg.MODEL.VFE.USE_NORM: True
2021-04-14 10:41:50,505   INFO  cfg.MODEL.VFE.NUM_FILTERS: [64]
2021-04-14 10:41:50,505   INFO  
cfg.MODEL.MAP_TO_BEV = edict()
2021-04-14 10:41:50,505   INFO  cfg.MODEL.MAP_TO_BEV.NAME: PointPillarScatter
2021-04-14 10:41:50,505   INFO  cfg.MODEL.MAP_TO_BEV.NUM_BEV_FEATURES: 64
2021-04-14 10:41:50,505   INFO  
cfg.MODEL.BACKBONE_2D = edict()
2021-04-14 10:41:50,505   INFO  cfg.MODEL.BACKBONE_2D.NAME: BaseBEVBackbone
2021-04-14 10:41:50,505   INFO  cfg.MODEL.BACKBONE_2D.LAYER_NUMS: [3, 5, 5]
2021-04-14 10:41:50,505   INFO  cfg.MODEL.BACKBONE_2D.LAYER_STRIDES: [2, 2, 2]
2021-04-14 10:41:50,505   INFO  cfg.MODEL.BACKBONE_2D.NUM_FILTERS: [64, 128, 256]
2021-04-14 10:41:50,505   INFO  cfg.MODEL.BACKBONE_2D.UPSAMPLE_STRIDES: [1, 2, 4]
2021-04-14 10:41:50,505   INFO  cfg.MODEL.BACKBONE_2D.NUM_UPSAMPLE_FILTERS: [128, 128, 128]
2021-04-14 10:41:50,505   INFO  
cfg.MODEL.DENSE_HEAD = edict()
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.NAME: AnchorHeadSingle
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.CLASS_AGNOSTIC: False
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.USE_DIRECTION_CLASSIFIER: True
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.DIR_OFFSET: 0.78539
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.DIR_LIMIT_OFFSET: 0.0
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.NUM_DIR_BINS: 2
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.ANCHOR_GENERATOR_CONFIG: [{'class_name': 'Car', 'anchor_sizes': [[3.9, 1.6, 1.56]], 'anchor_rotations': [0, 1.57], 'anchor_bottom_heights': [-1.78], 'align_center': False, 'feature_map_stride': 2, 'matched_threshold': 0.6, 'unmatched_threshold': 0.45}]
2021-04-14 10:41:50,505   INFO  
cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG = edict()
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.NAME: AxisAlignedTargetAssigner
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.POS_FRACTION: -1.0
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.SAMPLE_SIZE: 512
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.NORM_BY_NUM_EXAMPLES: False
2021-04-14 10:41:50,505   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.MATCH_HEIGHT: False
2021-04-14 10:41:50,506   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.BOX_CODER: ResidualCoder
2021-04-14 10:41:50,506   INFO  
cfg.MODEL.DENSE_HEAD.LOSS_CONFIG = edict()
2021-04-14 10:41:50,506   INFO  
cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS = edict()
2021-04-14 10:41:50,506   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.cls_weight: 1.0
2021-04-14 10:41:50,506   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.loc_weight: 2.0
2021-04-14 10:41:50,506   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.dir_weight: 0.2
2021-04-14 10:41:50,506   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
2021-04-14 10:41:50,506   INFO  
cfg.MODEL.POST_PROCESSING = edict()
2021-04-14 10:41:50,506   INFO  cfg.MODEL.POST_PROCESSING.RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
2021-04-14 10:41:50,506   INFO  cfg.MODEL.POST_PROCESSING.SCORE_THRESH: 0.1
2021-04-14 10:41:50,506   INFO  cfg.MODEL.POST_PROCESSING.OUTPUT_RAW_SCORE: False
2021-04-14 10:41:50,506   INFO  cfg.MODEL.POST_PROCESSING.EVAL_METRIC: kitti
2021-04-14 10:41:50,506   INFO  
cfg.MODEL.POST_PROCESSING.NMS_CONFIG = edict()
2021-04-14 10:41:50,506   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.MULTI_CLASSES_NMS: False
2021-04-14 10:41:50,506   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_TYPE: nms_gpu
2021-04-14 10:41:50,506   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_THRESH: 0.01
2021-04-14 10:41:50,506   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_PRE_MAXSIZE: 4096
2021-04-14 10:41:50,506   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_POST_MAXSIZE: 500
2021-04-14 10:41:50,506   INFO  
cfg.OPTIMIZATION = edict()
2021-04-14 10:41:50,506   INFO  cfg.OPTIMIZATION.BATCH_SIZE_PER_GPU: 4
2021-04-14 10:41:50,506   INFO  cfg.OPTIMIZATION.NUM_EPOCHS: 80
2021-04-14 10:41:50,506   INFO  cfg.OPTIMIZATION.OPTIMIZER: adam_onecycle
2021-04-14 10:41:50,506   INFO  cfg.OPTIMIZATION.LR: 0.003
2021-04-14 10:41:50,506   INFO  cfg.OPTIMIZATION.WEIGHT_DECAY: 0.01
2021-04-14 10:41:50,506   INFO  cfg.OPTIMIZATION.MOMENTUM: 0.9
2021-04-14 10:41:50,507   INFO  cfg.OPTIMIZATION.MOMS: [0.95, 0.85]
2021-04-14 10:41:50,507   INFO  cfg.OPTIMIZATION.PCT_START: 0.4
2021-04-14 10:41:50,507   INFO  cfg.OPTIMIZATION.DIV_FACTOR: 10
2021-04-14 10:41:50,507   INFO  cfg.OPTIMIZATION.DECAY_STEP_LIST: [35, 45]
2021-04-14 10:41:50,507   INFO  cfg.OPTIMIZATION.LR_DECAY: 0.1
2021-04-14 10:41:50,507   INFO  cfg.OPTIMIZATION.LR_CLIP: 1e-07
2021-04-14 10:41:50,507   INFO  cfg.OPTIMIZATION.LR_WARMUP: False
2021-04-14 10:41:50,507   INFO  cfg.OPTIMIZATION.WARMUP_EPOCH: 1
2021-04-14 10:41:50,507   INFO  cfg.OPTIMIZATION.GRAD_NORM_CLIP: 10
2021-04-14 10:41:50,507   INFO  cfg.TAG: car_kitti_pp
2021-04-14 10:41:50,507   INFO  cfg.EXP_GROUP_PATH: cfgs/kitti_models
2021-04-14 10:41:50,512   INFO  Database filter by min points Car: 135 => 134
2021-04-14 10:41:50,513   INFO  Database filter by difficulty Car: 134 => 0
2021-04-14 10:41:50,513   INFO  Loading KITTI dataset
2021-04-14 10:41:50,529   INFO  Total samples for KITTI dataset: 135
2021-04-14 10:41:52,357   INFO  PointPillar(
  (vfe): PillarVFE(
    (pfn_layers): ModuleList(
      (0): PFNLayer(
        (linear): Linear(in_features=10, out_features=64, bias=False)
        (norm): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      )
    )
  )
  (backbone_3d): None
  (map_to_bev_module): PointPillarScatter()
  (pfe): None
  (backbone_2d): BaseBEVBackbone(
    (blocks): ModuleList(
      (0): Sequential(
        (0): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
        (1): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), bias=False)
        (2): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (3): ReLU()
        (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (5): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (6): ReLU()
        (7): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (8): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (9): ReLU()
        (10): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (11): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (12): ReLU()
      )
      (1): Sequential(
        (0): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
        (1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), bias=False)
        (2): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (3): ReLU()
        (4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (5): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (6): ReLU()
        (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (8): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (9): ReLU()
        (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (11): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (12): ReLU()
        (13): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (14): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (15): ReLU()
        (16): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (17): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (18): ReLU()
      )
      (2): Sequential(
        (0): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
        (1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), bias=False)
        (2): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (3): ReLU()
        (4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (5): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (6): ReLU()
        (7): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (8): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (9): ReLU()
        (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (11): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (12): ReLU()
        (13): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (14): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (15): ReLU()
        (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (17): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (18): ReLU()
      )
    )
    (deblocks): ModuleList(
      (0): Sequential(
        (0): ConvTranspose2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (1): Sequential(
        (0): ConvTranspose2d(128, 128, kernel_size=(2, 2), stride=(2, 2), bias=False)
        (1): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (2): Sequential(
        (0): ConvTranspose2d(256, 128, kernel_size=(4, 4), stride=(4, 4), bias=False)
        (1): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
    )
  )
  (dense_head): AnchorHeadSingle(
    (cls_loss_func): SigmoidFocalClassificationLoss()
    (reg_loss_func): WeightedSmoothL1Loss()
    (dir_loss_func): WeightedCrossEntropyLoss()
    (conv_cls): Conv2d(384, 2, kernel_size=(1, 1), stride=(1, 1))
    (conv_box): Conv2d(384, 14, kernel_size=(1, 1), stride=(1, 1))
    (conv_dir_cls): Conv2d(384, 4, kernel_size=(1, 1), stride=(1, 1))
  )
  (point_head): None
  (roi_head): None
)
2021-04-14 10:41:52,358   INFO  **********************Start training cfgs/kitti_models/car_kitti_pp(default)**********************
epochs:   0%|                                                                                          | 0/80 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                     | 0/34 [00:00<?, ?it/s]
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 170, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/home/wu/OpenPCDet/tools/train_utils/train_utils.py", line 93, in train_model
    dataloader_iter=dataloader_iter
  File "/home/wu/OpenPCDet/tools/train_utils/train_utils.py", line 19, in train_one_epoch
    batch = next(dataloader_iter)
  File "/home/wu/anaconda3/envs/openpcdet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/wu/anaconda3/envs/openpcdet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/wu/anaconda3/envs/openpcdet/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wu/anaconda3/envs/openpcdet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wu/anaconda3/envs/openpcdet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wu/anaconda3/envs/openpcdet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wu/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 379, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/home/wu/OpenPCDet/pcdet/datasets/dataset.py", line 124, in prepare_data
    'gt_boxes_mask': gt_boxes_mask
  File "/home/wu/OpenPCDet/pcdet/datasets/augmentor/data_augmentor.py", line 93, in forward
    data_dict = cur_augmentor(data_dict=data_dict)
  File "/home/wu/OpenPCDet/pcdet/datasets/augmentor/database_sampler.py", line 177, in __call__
    sampled_boxes = np.stack([x['box3d_lidar'] for x in sampled_dict], axis=0).astype(np.float32)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/wu/anaconda3/envs/openpcdet/lib/python3.6/site-packages/numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

any ideas can be provided to solve it? Thanks in advance!

**Comment by TianchaoHuo** [comment]
I have  executed the command:
python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml 

and have generated following files:
![Screenshot from 2021-04-14 13-44-33](https://user-images.githubusercontent.com/37928758/114660254-90968100-9d27-11eb-828c-9679922c5c2f.png)

**Comment by TianchaoHuo** [comment]
I fixed it. I notice that there are two lines in above :

2021-04-14 10:41:50,512 INFO Database filter by min points Car: 135 => 134
2021-04-14 10:41:50,513 INFO Database filter by difficulty Car: 134 => 0

 I think there are no data from database since they are all filtered by difficulty. Therefore， I just comment the filter_by_difficulty: [-1] of the config file. Fortunately, it works ! But could anyone tell me what does so-called "difficulty"  here mean ?  

Thanks a lot~

**Comment by MartinHahner** [comment]
You can read about it [here](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d), just search for "difficulties".

**Comment by TianchaoHuo** [comment]
> You can read about it [here](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d), just search for "difficulties".

Thanks mate! Have a good day ^-^.
