### ISSUE TITLE
KITTI eval error  ( TypeError: can't unbox array from PyObject into native value.)

### ISSUE THREAD

**Issue by Dannyxu1031** [open-mmlab/OpenPCDet#564]
Some problem in  overlap_part = image_box_overlap(gt_boxes, dt_boxes)，and I cant fix it.help!

eval: 100%|#################################| 236/236 [12:32<00:00,  3.19s/it, recall_0.3=(16938, 16945) / 17558]
2021-06-16 02:48:55,344   INFO  *************** Performance of EPOCH 50 *****************
2021-06-16 02:48:55,344   INFO  Generate label finished(sec_per_example: 0.1995 second).
2021-06-16 02:48:55,344   INFO  recall_roi_0.3: 0.964688
2021-06-16 02:48:55,344   INFO  recall_rcnn_0.3: 0.965087
2021-06-16 02:48:55,344   INFO  recall_roi_0.5: 0.916619
2021-06-16 02:48:55,345   INFO  recall_rcnn_0.5: 0.924650
2021-06-16 02:48:55,345   INFO  recall_roi_0.7: 0.683449
2021-06-16 02:48:55,345   INFO  recall_rcnn_0.7: 0.732601
2021-06-16 02:48:55,351   INFO  Average predicted number of objects(3769 samples): 10.359
Traceback (most recent call last):
  File "test.py", line 200, in <module>
    main()
  File "test.py", line 196, in main
    eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test)
  File "test.py", line 64, in eval_single_ckpt
    result_dir=eval_output_dir, save_to_file=args.save_to_file
  File "/workspace/OpenPCDet-master/tools/eval_utils/eval_utils.py", line 113, in eval_one_epoch
    output_path=final_output_dir
  File "/workspace/OpenPCDet-master/pcdet/datasets/kitti/kitti_dataset.py", line 363, in evaluation
    ap_result_str, ap_dict = kitti_eval.get_official_eval_result(eval_gt_annos, eval_det_annos, class_names)
  File "/workspace/OpenPCDet-master/pcdet/datasets/kitti/kitti_object_eval_python/eval.py", line 675, in get_official_eval_result
    gt_annos, dt_annos, current_classes, min_overlaps, compute_aos, PR_detail_dict=PR_detail_dict)
  File "/workspace/OpenPCDet-master/pcdet/datasets/kitti/kitti_object_eval_python/eval.py", line 588, in do_eval
    min_overlaps, compute_aos)
  File "/workspace/OpenPCDet-master/pcdet/datasets/kitti/kitti_object_eval_python/eval.py", line 473, in eval_class
    rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)
  File "/workspace/OpenPCDet-master/pcdet/datasets/kitti/kitti_object_eval_python/eval.py", line 363, in calculate_iou_partly
    overlap_part = image_box_overlap(gt_boxes, dt_boxes)
TypeError: can't unbox array from PyObject into native value.  The object maybe of a different type

**Comment by Dannyxu1031** [comment]
I reinstall numba and then it work.

**Comment by Dannyxu1031** [comment]
Done

**Comment by Dannyxu1031** [comment]
finish
