### ISSUE TITLE
Unable to install OpenPCDet  run     raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by chowkamlee81** [open-mmlab/OpenPCDet#565]
Kindly help for the error below

File "/home/anaconda3/envs/E2VID/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/home/anaconda3/envs/E2VID/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    setup(
  File "/home/anaconda3/envs/E2VID/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/anaconda3/envs/E2VID/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/anaconda3/envs/E2VID/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/anaconda3/envs/E2VID/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/anaconda3/envs/E2VID/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/anaconda3/envs/E2VID/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/anaconda3/envs/E2VID/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/anaconda3/envs/E2VID/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/anaconda3/envs/E2VID/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/anaconda3/envs/E2VID/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/anaconda3/envs/E2VID/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/anaconda3/envs/E2VID/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/anaconda3/envs/E2VID/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/anaconda3/envs/E2VID/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/anaconda3/envs/E2VID/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/anaconda3/envs/E2VID/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/anaconda3/envs/E2VID/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/anaconda3/envs/E2VID/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by chowkamlee81** [comment]
use torch<=1.7
