### ISSUE TITLE
Nvidia 2080Ti - RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by darrenjkt** [open-mmlab/OpenPCDet#624]
Hi thank you for your code. I managed to get the code successfully running on a 1080Ti and 1080. 

My problem is that I just installed a 2080Ti, ran the training script for KITTI second_iou.yaml and it crashes in the iou3d_nms_utils.py file due to no kernel image. The odd thing is that in interactive python, cuda is detected and I can do operations with `torch.rand`. 

Are there additional compilation instructions for a 2080Ti? 

```
2021-09-07 02:47:37,082   INFO  **********************Start training kitti_models/second_iou(default)**********************
INFO - 2021-09-07 02:47:37,082 - train - **********************Start training kitti_models/second_iou(default)**********************
epochs:   0%|                                                           | 0/80 [00:00<?, ?it/s/OpenPCDet/pcdet/models/dense_heads/target_assigner/axis_aligned_target_assigner.py:154: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  anchors_with_max_overlap = (anchor_by_gt_overlap == gt_to_anchor_max).nonzero()[:, 0]
Error!
Error!
Error!
Error!
epochs:   0%|                                                           | 0/80 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 242, in <module>
    main()
  File "train.py", line 198, in main
    train_model(
  File "/OpenPCDet/tools/train_utils/train_utils.py", line 90, in train_model
    accumulated_iter = train_one_epoch(
  File "/OpenPCDet/tools/train_utils/train_utils.py", line 38, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/OpenPCDet/pcdet/models/__init__.py", line 42, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/OpenPCDet/pcdet/models/detectors/second_net_iou.py", line 16, in forward
    batch_dict = cur_module(batch_dict)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/OpenPCDet/pcdet/models/roi_heads/second_head.py", line 121, in forward
    targets_dict = self.assign_targets(batch_dict)
  File "/OpenPCDet/pcdet/models/roi_heads/roi_head_template.py", line 107, in assign_targets
    targets_dict = self.proposal_target_layer.forward(batch_dict)
  File "/OpenPCDet/pcdet/models/roi_heads/target_assigner/proposal_target_layer.py", line 32, in forward
    batch_rois, batch_gt_of_rois, batch_roi_ious, batch_roi_scores, batch_roi_labels = self.sample_rois_for_rcnn(
  File "/OpenPCDet/pcdet/models/roi_heads/target_assigner/proposal_target_layer.py", line 101, in sample_rois_for_rcnn
    max_overlaps, gt_assignment = self.get_max_iou_with_same_class(
  File "/OpenPCDet/pcdet/models/roi_heads/target_assigner/proposal_target_layer.py", line 225, in get_max_iou_with_same_class
    iou3d = iou3d_nms_utils.boxes_iou3d_gpu(cur_roi, cur_gt)  # (M, N)
  File "/OpenPCDet/pcdet/ops/iou3d_nms/iou3d_nms_utils.py", line 69, in boxes_iou3d_gpu
    max_of_min = torch.max(boxes_a_height_min, boxes_b_height_min)
RuntimeError: CUDA error: no kernel image is available for execution on the device

```

**Environment**
I built a [docker image](https://hub.docker.com/layers/158954441/darrenjkt/openpcdet/v0.3.0/images/sha256-00c2313a9c01ecb5d98220041ca5c682bdd71ec17696dd7f60e8fa82cf1cae13?context=repo) which was built upon the [scrin/dev-spconv](https://hub.docker.com/layers/scrin/dev-spconv/c0f7284c51205f259cb270747259c01cd03cc2ed/images/sha256-478269149f5478f525af0872d54416442c186274a559bd94c4620b78d0b33817?context=explore) as base image. This works well on my 1080Ti and 1080.

The code snippet:
```
import torch
import sys
print('A', sys.version)
print('B', torch.__version__)
print('C', torch.cuda.is_available())
print('D', torch.backends.cudnn.enabled)
device = torch.device('cuda')
print('E', torch.cuda.get_device_properties(device))
print('F', torch.tensor([1.0, 2.0]).cuda())
```
Gave me 
```
A 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
B 1.7.1+cu110
C True
D True
E _CudaDeviceProperties(name='NVIDIA GeForce RTX 2080 Ti', major=7, minor=5, total_memory=11019MB, multi_processor_count=68)
F tensor([1., 2.], device='cuda:0')
```

**Things I've tried:**
- `pip3 install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html -U` though I just get a different error, which is related to the incompatibility of this repo with the version
- Added extra_compile_args for compute_75 and sm_75 to setup.py and rebuilt with 
```
python setup.py clean
python setup.py build develop
```
![image](https://user-images.githubusercontent.com/39115809/132298384-395adbe7-8893-4396-8960-d662d965ec21.png)

**Comment by darrenjkt** [comment]
In case anyone is interested, I managed to solve the problem simply by deleting the previous /build and /pcdet.egg.info folders then re-installing the repo with 
```
python setup.py develop
```

**Comment by Petros626** [comment]
@darrenjkt only these two folders, with letting everything else unchanged and just run the command again?
