### ISSUE TITLE
Tensor dimension mismatch in PointPillar BaseBEVBackbone

### ISSUE THREAD

**Issue by dmahajan1** [open-mmlab/OpenPCDet#634]
Hello, I am using a custom dataset that has been converted to kitti format, and when I run train.py, I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/openpcdet_v030/tools/train.py", line 201, in <module>
    main()
  File "/openpcdet_v030/tools/train.py", line 173, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/openpcdet_v030/tools/train_utils/train_utils.py", line 93, in train_model
    dataloader_iter=dataloader_iter
  File "/openpcdet_v030/tools/train_utils/train_utils.py", line 38, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/openpcdet_v030/pcdet/models/__init__.py", line 30, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/openpcdet_v030/pcdet/models/detectors/pointpillar.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/openpcdet_v030/pcdet/models/backbones_2d/base_bev_backbone.py", line 106, in forward
    x = torch.cat(ups, dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 472 and 469
```

When I print the values of `self.blocks[i](x)` for each iteration of `forward()` in base_bev_backbone.py, I get the following dimensions:
torch.Size([4, 64, 469, 541])
torch.Size([4, 128, 235, 271])
torch.Size([4, 256, 118, 136])

Are the dimensions supposed to match? I don't see how that is possible if the layers have 64, 128, and 256 filters respectively.

Thank you

**Comment by jihanyang** [comment]
Please refer #253 to set the voxel size. This might caused by inccoret feature map size due to incorrect voxel size.

**Comment by dmahajan1** [comment]
That was exactly it, I tried a few different voxel sizes and found one that produces matching tensor dimensions. Thanks!
