### ISSUE TITLE
CUDA error: too many resources requested for launch

### ISSUE THREAD

**Issue by jonasmeyer1** [open-mmlab/OpenPCDet#659]
I want to use OpenPCDet v0.3 on a NVIDIA Jetson TX2 with the following specifications:

Ubuntu 18.04
JetPack 4.4
CUDA 10.2
CuDNN 8.0
Python 3.6.9
pytorch 1.6.0
spconv 1.2.1

All the 3D object detection methods which relies on spconv (SECOND, PartA2 etc.) failed due to a CUDA error ```RuntimeError: CUDA error: too many resources requested for launch```. The other methods, like PointRCNN or PointPillars worked properly. Does anyone know how to solve this issue?

Thanks

```
Traceback (most recent call last):
  File "extract_bb.py", line 146, in <module>
    main()
  File "extract_bb.py", line 116, in main
    pred_dicts, _ = model.forward(data_dict)
  File "/home/nvidia/MTh_meyj/Software/OpenPCDet/pcdet/models/detectors/voxel_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/MTh_meyj/Software/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone.py", line 147, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/.local/lib/python3.6/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nvidia/.local/lib/python3.6/site-packages/spconv/conv.py", line 199, in forward
    outids.shape[0], self.algo)
  File "/home/nvidia/.local/lib/python3.6/site-packages/spconv/functional.py", line 94, in forward
    algo=algo)
  File "/home/nvidia/.local/lib/python3.6/site-packages/spconv/ops.py", line 120, in indice_conv
    int(inverse), int(subm), algo)
RuntimeError: CUDA error: too many resources requested for launch
```

**Comment by jonasmeyer1** [comment]
For the solution, see this Issue.
https://github.com/traveller59/spconv/issues/362
