### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by JianyyuWang** [open-mmlab/OpenPCDet#705]
When I execute python setup.py develop
I got this error:
running develop
running egg_info
writing pcdet.egg-info/PKG-INFO
writing dependency_links to pcdet.egg-info/dependency_links.txt
writing requirements to pcdet.egg-info/requires.txt
writing top-level names to pcdet.egg-info/top_level.txt
reading manifest file 'pcdet.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'pcdet.egg-info/SOURCES.txt'
running build_ext
building 'pcdet.ops.iou3d_nms.iou3d_nms_cuda' extension
Emitting ninja build file /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/4] /usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/bin/nvcc -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/include/python3.8 -c -c /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.cu -o /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=sm_70 -std=c++14
FAILED: /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o 
/usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/bin/nvcc -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/include/python3.8 -c -c /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.cu -o /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=sm_70 -std=c++14
/bin/sh: 1: /usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/bin/nvcc: not found
[2/4] c++ -MMD -MF /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_cpu.o.d -pthread -B /home/wangjianyu/config/anaconda3/envs/OpenPCDet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/include/python3.8 -c -c /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_cpu.cpp -o /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_cpu.o 
c++ -MMD -MF /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_cpu.o.d -pthread -B /home/wangjianyu/config/anaconda3/envs/OpenPCDet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/include/python3.8 -c -c /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_cpu.cpp -o /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_cpu.cpp:10:
/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
/home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_cpu.cpp:12:10: fatal error: cuda.h: 没有那个文件或目录
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
[3/4] c++ -MMD -MF /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o.d -pthread -B /home/wangjianyu/config/anaconda3/envs/OpenPCDet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/include/python3.8 -c -c /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_api.cpp -o /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o 
c++ -MMD -MF /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o.d -pthread -B /home/wangjianyu/config/anaconda3/envs/OpenPCDet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/include/python3.8 -c -c /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_api.cpp -o /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms_api.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_api.cpp:2:
/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
/home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms_api.cpp:4:10: fatal error: cuda.h: 没有那个文件或目录
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
[4/4] c++ -MMD -MF /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms.o.d -pthread -B /home/wangjianyu/config/anaconda3/envs/OpenPCDet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/include/python3.8 -c -c /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms.cpp -o /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms.o 
c++ -MMD -MF /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms.o.d -pthread -B /home/wangjianyu/config/anaconda3/envs/OpenPCDet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/TH -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda/bin:/usr/local/cuda:/usr/local/cuda:/include -I/home/wangjianyu/config/anaconda3/envs/OpenPCDet/include/python3.8 -c -c /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms.cpp -o /home/wangjianyu/workspace/OpenPCDet/build/temp.linux-x86_64-3.8/pcdet/ops/iou3d_nms/src/iou3d_nms.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms.cpp:8:
/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
/home/wangjianyu/workspace/OpenPCDet/pcdet/ops/iou3d_nms/src/iou3d_nms.cpp:10:10: fatal error: cuda.h: 没有那个文件或目录
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1509, in _run_ninja_build
    subprocess.run(
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    setup(
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 469, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1228, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/wangjianyu/config/anaconda3/envs/OpenPCDet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
______________________________________________________________________________________________________________________________________
my env is:
pytorch=1.6.0 cuda=10.2
spconv=spconv-cu102

**Comment by guanglei-maker** [comment]
Same question.Have you solved it？

**Comment by JianyyuWang** [comment]
not yet

**Comment by jihanyang** [comment]
Can you import spconv normally?

**Comment by JianyyuWang** [comment]
yes spconv==2.X

**Comment by gashel** [comment]
I got the same question when the torch version was 0.9.0.
And I reinstall the torch with version 0.10.0，then the question was solved.
My enviroment was cuda11.1+python3.6+torch1.10.0-cu111+spconv-cu111。
When I ran the commad "pip install -r requirements.txt"，I did not install torch and torchvision. 
Instead，I installed torch with "pip install XXX.whl”

**Comment by Clichong** [comment]
same question
