### ISSUE TITLE
Kitti AssertionError

### ISSUE THREAD

**Issue by yun9993** [open-mmlab/OpenPCDet#753]
Traceback (most recent call last):
  File "/root/anaconda3/envs/environment_name/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/environment_name/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data8/lyp/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 478, in <module>
    create_kitti_infos(
  File "/data8/lyp/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 442, in create_kitti_infos
    kitti_infos_train = dataset.get_infos(num_workers=workers, has_label=True, count_inside_pts=True)
  File "/data8/lyp/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 222, in get_infos
    return list(infos)
  File "/root/anaconda3/envs/environment_name/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/root/anaconda3/envs/environment_name/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/root/anaconda3/envs/environment_name/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/root/anaconda3/envs/environment_name/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data8/lyp/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 173, in process_single_scene
    obj_list = self.get_label(sample_idx)
  File "/data8/lyp/OpenPCDet/pcdet/datasets/kitti/kitti_dataset.py", line 90, in get_label
    assert label_file.exists()
AssertionError

**Comment by CopleManba** [comment]
Did you have solve this question? I met the same question.
