### ISSUE TITLE
run demo.py   TypeError: safe_load() got an unexpected keyword argument 'Loader'

### ISSUE THREAD

**Issue by elegentbamboo** [open-mmlab/OpenPCDet#825]
(HDMapNet) l@l:/Project/pycharm_project/OpenPCDet-master/tools$ python demo.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml \
>     --ckpt pv_rcnn_8369.pth \
>     --data_path ../data/kitti/training/velodyne/000008.bin
Traceback (most recent call last):
  File "/Project/pycharm_project/OpenPCDet-master/pcdet/config.py", line 55, in merge_new_config
    yaml_config = yaml.safe_load(f, Loader=yaml.FullLoader)
TypeError: safe_load() got an unexpected keyword argument 'Loader'

During handling of the above exception, another exception [occurred:]

Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    main()
  File "demo.py", line 80, in main
    args, cfg = parse_config()
  File "demo.py", line 74, in parse_config
    cfg_from_yaml_file(args.cfg_file, cfg)
  File "/Project/pycharm_project/OpenPCDet-master/pcdet/config.py", line 78, in cfg_from_yaml_file
    merge_new_config(config=config, new_config=new_config)
  File "/Project/pycharm_project/OpenPCDet-master/pcdet/config.py", line 66, in merge_new_config
    merge_new_config(config[key], val)
  File "/Project/pycharm_project/OpenPCDet-master/pcdet/config.py", line 57, in merge_new_config
    yaml_config = yaml.safe_load(f)
  File "/software/Anaconda3/envs/HDMapNet/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/software/Anaconda3/envs/HDMapNet/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/software/Anaconda3/envs/HDMapNet/lib/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/software/Anaconda3/envs/HDMapNet/lib/python3.7/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/software/Anaconda3/envs/HDMapNet/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/software/Anaconda3/envs/HDMapNet/lib/python3.7/site-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "cfgs/dataset_configs/kitti_dataset.yaml", line 2, column 1

How can I solve the problem?

**Comment by beizhengren** [comment]
how did you solve it? 
thanks
