### ISSUE TITLE
num_features == voxels.dim(2) assert faild for nuscenes

### ISSUE THREAD

**Issue by YCAyca** [open-mmlab/OpenPCDet#852]
Hello, when I try to make inference using nuscene dataset with my nuscene trained cbgs_pp_multihead.yaml model, I get an error as below. 

Traceback (most recent call last):
  File "demo.py", line 135, in <module>
    main()
  File "demo.py", line 112, in main
    for idx, data_dict in enumerate(demo_dataset):
  File "demo.py", line 70, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/home/yagmur/Desktop/OpenPCDet/pcdet/datasets/dataset.py", line 149, in prepare_data
    data_dict = self.data_processor.forward(
  File "/home/yagmur/Desktop/OpenPCDet/pcdet/datasets/processor/data_processor.py", line 210, in forward
    data_dict = cur_processor(data_dict=data_dict)
  File "/home/yagmur/Desktop/OpenPCDet/pcdet/datasets/processor/data_processor.py", line 135, in transform_points_to_voxels
    voxel_output = self.voxel_generator.generate(points)
  File "/home/yagmur/Desktop/OpenPCDet/pcdet/datasets/processor/data_processor.py", line 55, in generate
    voxel_output = self._voxel_generator.point_to_voxel(tv.from_numpy(points))
RuntimeError: /io/build/temp.linux-x86_64-3.8/spconv/build/src/csrc/sparse/all/ops_cpu3d/Point2VoxelCPU/Point2VoxelCPU_point_to_voxel_static.cc(21)
num_features == voxels.dim(2) assert faild. your points num features doesn't equal to voxel.

I was wondering what is NUM_POINT_FEATURES: 5 parameter in nuscene_dataset.yaml file for data augmentation part and how to give a compatible size for this param.

**Comment by YCAyca** [comment]
Ahh 824 solved thanks
