### ISSUE TITLE
How to get the model graph

### ISSUE THREAD

**Issue by makeradventures** [open-mmlab/OpenPCDet#857]
Hello, 
I have a very specific problem I have been struggling with for some time now: Given the architecture of OpenPCDet I am confused how to get the graph of the model! 
I tried following those instructions: [stackoverflow](https://stackoverflow.com/questions/52468956/how-do-i-visualize-a-net-in-pytorch)
but all of them fail! Going down the rabbit hole there seems to be a problem with `torch.jit.trace`
when adding this line to the demo.py:
`module_trace = torch.jit.trace(model.forward, data_dict) `
in here:
```
    with torch.no_grad():
        for idx, data_dict in enumerate(demo_dataset):
            logger.info(f'Visualized sample index: \t{idx + 1}')
            data_dict = demo_dataset.collate_batch([data_dict])    
            load_data_to_gpu(data_dict)
            #trying to get the model trace:
            module_trace = torch.jit.trace(model.forward, data_dict)   
            pred_dicts, _ = model.forward(data_dict)
            V.draw_scenes(
                points=data_dict['points'][:, 1:], ref_boxes=pred_dicts[0]['pred_boxes'],
                ref_scores=pred_dicts[0]['pred_scores'], ref_labels=pred_dicts[0]['pred_labels']
            )
            if not OPEN3D_FLAG:
                mlab.show(stop=True)
```
I get the following error:
```
Traceback (most recent call last):
  File "demo.py", line 114, in <module>
    main()
  File "demo.py", line 101, in main
    module_trace = torch.jit.trace(model.forward, data_dict)   
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_trace.py", line 767, in trace
    _module_class,
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_trace.py", line 965, in trace_module
    argument_names,
RuntimeError: Tracer cannot infer type of ({'points': tensor([[ 0.0000, 43.8890,  0.0840,  1.6930,  0.0000],
        [ 0.0000, 43.2010,  0.2180,  1.6700,  0.0000],
        [ 0.0000, 42.3970,  0.3470,  1.6430,  0.0000],
        ...,
        [ 0.0000,  3.6960, -1.3980, -1.7260,  0.3100],
        [ 0.0000,  3.7170, -1.3990, -1.7360,  0.3500],
        [ 0.0000,  3.7240, -1.3890, -1.7370,  0.0000]], device='cuda:0'), 'frame_id': array([0]), 'use_lead_xyz': tensor([1.], device='cuda:0'), 'voxels': tensor([[[22.0860,  3.9210,  0.9680,  0.3200],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[21.8400,  3.9480,  0.9600,  0.2700],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[21.6520,  3.9840,  0.9540,  0.3500],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        ...,

        [[ 1.3970,  4.0270, -1.7210,  0.1300],
         [ 1.3870,  4.0420, -1.7260,  0.2000],
         [ 1.3710,  4.0340, -1.7200,  0.1100],
         [ 1.3600,  4.0440, -1.7220,  0.1800],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 1.3440,  4.0380, -1.7180,  0.2200],
         [ 1.3190,  4.0490, -1.7190,  0.2000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 1.3340,  4.0520, -1.7220,  0.2300],
         [ 1.3120,  4.0500, -1.7180,  0.0900],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]], device='cuda:0'), 'voxel_coords': tensor([[  0.,  39., 878., 441.],
        [  0.,  39., 878., 436.],
        [  0.,  39., 879., 433.],
        ...,
        [  0.,  12., 880.,  27.],
        [  0.,  12., 880.,  26.],
        [  0.,  12., 881.,  26.]], device='cuda:0'), 'voxel_num_points': tensor([1., 1., 1.,  ..., 4., 2., 2.], device='cuda:0'), 'batch_size': 1},)
:Only tensors and (possibly nested) tuples of tensors, lists, or dictsare supported as inputs or outputs of traced functions, but instead got value of type ndarray.

```

Does anyone know how to get the model graph of the network in OpenPCDet?

Thanks in advance!

**Comment by makeradventures** [comment]
I solved this problem by converting frame_id and batch_size to a torch.tensor:
```
    with torch.no_grad():
        for idx, data_dict in enumerate(demo_dataset):
            logger.info(f'Visualized sample index: \t{idx + 1}')
            data_dict = demo_dataset.collate_batch([data_dict]) 
            print("converting frame id, batch size ...")
            data_dict['frame_id']=torch.tensor(data_dict['frame_id'])
            data_dict['batch_size']=torch.tensor(data_dict['batch_size'])   
            load_data_to_gpu(data_dict)
            #trying to get the model trace:
            model_trace = torch.jit.trace(model.forward, data_dict)   
            pred_dicts, _ = model.forward(data_dict)
            V.draw_scenes(
                points=data_dict['points'][:, 1:], ref_boxes=pred_dicts[0]['pred_boxes'],
                ref_scores=pred_dicts[0]['pred_scores'], ref_labels=pred_dicts[0]['pred_labels']
            )
            if not OPEN3D_FLAG:
                mlab.show(stop=True)
```

but now I get the untraceable error Segmentation fault (core dumped):
```
/usr/local/lib/python3.7/dist-packages/spconv/pytorch/core.py:149: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert len(spatial_shape) == ndim, "spatial shape must equal to ndim"
/usr/local/lib/python3.7/dist-packages/spconv/pytorch/core.py:151: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert batch_size > 0
/usr/local/lib/python3.7/dist-packages/spconv/pytorch/core.py:160: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  grid = torch.Tensor()  # empty tensor
/usr/local/lib/python3.7/dist-packages/spconv/pytorch/conv.py:187: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  1] == self.in_channels, "channel size mismatch"
/usr/local/lib/python3.7/dist-packages/spconv/pytorch/modules.py:140: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if input.indices.shape[0] != 0:
/usr/local/lib/python3.7/dist-packages/spconv/pytorch/conv.py:480: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if inp.indices.shape[0] != datas.indices.shape[0]:
/usr/local/lib/python3.7/dist-packages/spconv/pytorch/ops.py:428: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  pair_mask_bwd = torch.Tensor()
/usr/local/lib/python3.7/dist-packages/spconv/pytorch/ops.py:477: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  mask_argsort_bwd = torch.Tensor()
/home/docker/data/OpenPCDet/pcdet/models/backbones_2d/base_bev_backbone.py:95: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  stride = int(spatial_features.shape[2] / x.shape[2])
/home/docker/data/OpenPCDet/pcdet/models/detectors/detector3d_template.py:214: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_preds.shape[1] in [1, self.num_class]
/home/docker/data/OpenPCDet/pcdet/models/model_utils/model_nms_utils.py:14: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if box_scores.shape[0] > 0:
/home/docker/data/OpenPCDet/pcdet/models/model_utils/model_nms_utils.py:15: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  box_scores_nms, indices = torch.topk(box_scores, k=min(nms_config.NMS_PRE_MAXSIZE, box_scores.shape[0]))
/home/docker/data/OpenPCDet/pcdet/models/model_utils/model_nms_utils.py:15: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  box_scores_nms, indices = torch.topk(box_scores, k=min(nms_config.NMS_PRE_MAXSIZE, box_scores.shape[0]))
/home/docker/data/OpenPCDet/pcdet/ops/iou3d_nms/iou3d_nms_utils.py:91: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.shape[1] == 7
Segmentation fault (core dumped)

```

**Comment by makeradventures** [comment]
There may be some connection to #828!

**Comment by makeradventures** [comment]
Maybe it is just a bug and one can do nothing about it:
https://github.com/pytorch/pytorch/issues/19349

I think I give up, but I would really appreciate it, if someone could tell me how to visualize the graph of an OpenPCDet model!

**Comment by gzchenjiajun** [comment]
same problem ..
IndexError: slice() cannot be applied to a 0-dim tensor.
how to solve
