### ISSUE TITLE
how to show the result of  demo.py in docker ? Thanks

### ISSUE THREAD

**Issue by MiaoRain** [open-mmlab/OpenPCDet#869]
how to show the result of  demo.py in docker? Thanks
any suggestions will be appreciated!

```
 python3 demo.py --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt /root/workspace/0work-3D/OpenPCDet/output/kitti_models/pointpillar/default/ckpt/checkpoint_epoch_100.pth --data_path /root/workspace/0work-3D/OpenPCDet/data/kitti/training/velodyne/000008.bin
['/root/workspace/0work-3D/OpenPCDet/tools', '/opt/conda/lib/python37.zip', '/opt/conda/lib/python3.7', '/opt/conda/lib/python3.7/lib-dynload', '/opt/conda/lib/python3.7/site-packages', '/opt/conda/lib/python3.7/site-packages/future-0.18.2-py3.7.egg', '/workspace/mmsegmentation', '/opt/conda/lib/python3.7/site-packages/SharedArray-3.2.1-py3.7-linux-x86_64.egg', '/root/workspace/0work-3D/OpenPCDet', '/opt/conda/lib/python3.7/site-packages/IPython/extensions']
pcdet.datasets.kitti.kitti_dataset
pcdet.datasets.kitti
2022-03-15 06:33:15,163   INFO  -----------------Quick Demo of OpenPCDet-------------------------
2022-03-15 06:33:15,164   INFO  Total number of samples: 	1
/root/workspace/0work-3D/OpenPCDet/output/kitti_models/pointpillar/default/ckpt/checkpoint_epoch_100.pth
2022-03-15 06:33:16,428   INFO  ==> Loading parameters from checkpoint /root/workspace/0work-3D/OpenPCDet/output/kitti_models/pointpillar/default/ckpt/checkpoint_epoch_100.pth to CPU
2022-03-15 06:33:16,450   INFO  ==> Checkpoint trained from version: pcdet+0.5.2+a991105
2022-03-15 06:33:16,456   INFO  ==> Done (loaded 127/127)
2022-03-15 06:33:16,466   INFO  Visualized sample index: 	1
/root/workspace/0work-3D/OpenPCDet/pcdet/models/model_utils/model_nms_utils.py:23: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629403081/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  original_idxs = scores_mask.nonzero().view(-1)
No protocol specified
[Open3D WARNING] GLFW Error: X11: Failed to open display :1
[Open3D WARNING] Failed to initialize GLFW
Traceback (most recent call last):
  File "demo.py", line 114, in <module>
    main()
  File "demo.py", line 104, in main
    ref_scores=pred_dicts[0]['pred_scores'], ref_labels=pred_dicts[0]['pred_labels']
  File "/root/workspace/0work-3D/OpenPCDet/tools/visual_utils/open3d_vis_utils.py", line 49, in draw_scenes
    vis.get_render_option().point_size = 1.0
AttributeError: 'NoneType' object has no attribute 'point_size'
```

**Comment by LouisSF** [comment]
Hey, I don't think this is recommended, you should probably use Open3D to save results as images to a shared folder with the main server (not Docker). You can then visualize them out of the container. 
If you really must visualize them within Docker, maybe look at references such as this [StackOverflow issue](https://stackoverflow.com/questions/16296753/can-you-run-gui-applications-in-a-linux-docker-container) or other [tutorials](https://www.cloudsavvyit.com/10520/how-to-run-gui-applications-in-a-docker-container/)

**Comment by MiaoRain** [comment]
> Hey, I don't think this is recommended, you should probably use Open3D to save results as images to a shared folder with the main server (not Docker). You can then visualize them out of the container. If you really must visualize them within Docker, maybe look at references such as this [StackOverflow issue](https://stackoverflow.com/questions/16296753/can-you-run-gui-applications-in-a-linux-docker-container) or other [tutorials](https://www.cloudsavvyit.com/10520/how-to-run-gui-applications-in-a-docker-container/)

Thanks a lot!

**Comment by Zishuo-9** [comment]
How to save the results?
