### ISSUE TITLE
python train.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml 

### ISSUE THREAD

**Issue by zhen12079** [open-mmlab/OpenPCDet#878]
python train.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml 
Traceback (most recent call last):
  File "train.py", line 204, in <module>
    main()
  File "train.py", line 62, in main
    args, cfg = parse_config()
  File "train.py", line 51, in parse_config
    cfg_from_yaml_file(args.cfg_file, cfg)
  File "../pcdet/config.py", line 72, in cfg_from_yaml_file
    with open(cfg_file, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

can you help me ? thanks!

**Comment by sshaoshuai** [comment]
No idea about this, maybe you need to check why your cfg_file is None at this line.
