### ISSUE TITLE
valueError when create_waymo_infos due to 0 box

### ISSUE THREAD

**Issue by zyl1336110861** [open-mmlab/OpenPCDet#881]
@lindahua Hi, Thank you very much for your sharing! When I try to processed the full waymo datasets using the create_waymo_infos function, I encounter the following problems:

Traceback (most recent call last):
  File "/home/xxx/.conda/envs/voxel/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxx/.conda/envs/voxel/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "xxx/OpenPCDet/pcdet/datasets/waymo/waymo_dataset.py", line 501, in <module>
    processed_data_tag=dataset_cfg.PROCESSED_DATA_TAG
  File "xxx/OpenPCDet/pcdet/datasets/waymo/waymo_dataset.py", line 457, in create_waymo_infos
    sampled_interval=1
  File "xxx/OpenPCDet/pcdet/datasets/waymo/waymo_dataset.py", line 114, in get_infos
    total=len(sample_sequence_file_list)))
  File "/home/xxx/.conda/envs/voxel/lib/python3.7/site-packages/tqdm-4.62.3-py3.7.egg/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/xxx/.conda/envs/voxel/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/xxx/.conda/envs/voxel/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/xxx/.conda/envs/voxel/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/xxx/.conda/envs/voxel/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "xxx/OpenPCDet/pcdet/datasets/waymo/waymo_utils.py", line 313, in process_single_sequence
    annotations = generate_labels(frame,calib)
  File "xxx/OpenPCDet/pcdet/datasets/waymo/waymo_utils.py", line 53, in generate_labels
    pts_rect = calib.lidar_to_rect(np.array(locations))
  File "xxx/OpenPCDet/pcdet/utils/calibration_kitti.py", line 70, in lidar_to_rect
    pts_lidar_hom = self.cart_to_hom(pts_lidar)
  File "xxx/OpenPCDet/pcdet/utils/calibration_kitti.py", line 47, in cart_to_hom
    pts_hom = np.hstack((pts, np.ones((pts.shape[0], 1), dtype=np.float32)))
  File "<__array_function__ internals>", line 6, in hstack
  File "/home/xxx/.local/lib/python3.7/site-packages/numpy/core/shape_base.py", line 344, in hstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

I think maybe the reason is the 0 number of gt_box center location. How to solve this problem properly?

**Comment by zyl1336110861** [comment]
> @lindahua Hi, Thank you very much for your sharing! When I try to processed the full waymo datasets using the create_waymo_infos function, I encounter the following problems:
> 
> Traceback (most recent call last): File "/home/xxx/.conda/envs/voxel/lib/python3.7/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/home/xxx/.conda/envs/voxel/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "xxx/OpenPCDet/pcdet/datasets/waymo/waymo_dataset.py", line 501, in processed_data_tag=dataset_cfg.PROCESSED_DATA_TAG File "xxx/OpenPCDet/pcdet/datasets/waymo/waymo_dataset.py", line 457, in create_waymo_infos sampled_interval=1 File "xxx/OpenPCDet/pcdet/datasets/waymo/waymo_dataset.py", line 114, in get_infos total=len(sample_sequence_file_list))) File "/home/xxx/.conda/envs/voxel/lib/python3.7/site-packages/tqdm-4.62.3-py3.7.egg/tqdm/std.py", line 1180, in **iter** for obj in iterable: File "/home/xxx/.conda/envs/voxel/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator yield fs.pop().result() File "/home/xxx/.conda/envs/voxel/lib/python3.7/concurrent/futures/_base.py", line 425, in result return self.__get_result() File "/home/xxx/.conda/envs/voxel/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result raise self._exception File "/home/xxx/.conda/envs/voxel/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "xxx/OpenPCDet/pcdet/datasets/waymo/waymo_utils.py", line 313, in process_single_sequence annotations = generate_labels(frame,calib) File "xxx/OpenPCDet/pcdet/datasets/waymo/waymo_utils.py", line 53, in generate_labels pts_rect = calib.lidar_to_rect(np.array(locations)) File "xxx/OpenPCDet/pcdet/utils/calibration_kitti.py", line 70, in lidar_to_rect pts_lidar_hom = self.cart_to_hom(pts_lidar) File "xxx/OpenPCDet/pcdet/utils/calibration_kitti.py", line 47, in cart_to_hom pts_hom = np.hstack((pts, np.ones((pts.shape[0], 1), dtype=np.float32))) File "<**array_function** internals>", line 6, in hstack File "/home/xxx/.local/lib/python3.7/site-packages/numpy/core/shape_base.py", line 344, in hstack return _nx.concatenate(arrs, 0) File "<**array_function** internals>", line 6, in concatenate ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)
> 
> I think maybe the reason is the 0 number of gt_box center location. How to solve this problem properly?
