### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s) 280363, 280364) exited unexpectedly

### ISSUE THREAD

**Issue by udacityyy** [open-mmlab/OpenPCDet#969]
Hello, first of all, thank you for releasing this project
I am facing a problem; when I run the following command  : 
python train.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml  --batch_size 1 --epochs 80 --workers 2 --save_to_file

I get this as a result : 
2022-05-13 17:33:45,349   INFO  **********************Start training kitti_models/pv_rcnn(default)**********************
epochs:   0%|                                                                                                                                                   | 0/80 [00:00<?, ?it/s]None
None
Exception ignored in: <function _releaseLock at 0x7fc5f6b61a60>
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 227, in _releaseLock
    def _releaseLock():
  File "/nfs/home/sc98255/.local/share/virtualenvs/OpenPCDet-9UU-mtWz/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 280265) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
None
None
epochs:   0%|                                                                                                                                                   | 0/80 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                                                                            | 0/3712 [00:00<?, ?it/s]
  File "/nfs/home/sc98255/.local/share/virtualenvs/OpenPCDet-9UU-mtWz/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
  File "/nfs/home/sc98255/.local/share/virtualenvs/OpenPCDet-9UU-mtWz/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 280363) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 204, in <module>
    main()
  File "train.py", line 156, in main
    train_model(
  File "/nfs/home/sc98255/OpenPCDet/tools/train_utils/train_utils.py", line 111, in train_model
    accumulated_iter = train_one_epoch(
  File "/nfs/home/sc98255/OpenPCDet/tools/train_utils/train_utils.py", line 25, in train_one_epoch
    batch = next(dataloader_iter)
  File "/nfs/home/sc98255/.local/share/virtualenvs/OpenPCDet-9UU-mtWz/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/nfs/home/sc98255/.local/share/virtualenvs/OpenPCDet-9UU-mtWz/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/nfs/home/sc98255/.local/share/virtualenvs/OpenPCDet-9UU-mtWz/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1142, in _get_data
    success, data = self._try_get_data()
  File "/nfs/home/sc98255/.local/share/virtualenvs/OpenPCDet-9UU-mtWz/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 280363, 280364) exited unexpectedly

**********************************

But when I put 0 workers, it ouputs me this : 
![image](https://user-images.githubusercontent.com/74137200/168318374-fdb5e378-0187-42ce-96f5-f48f728aa7c9.png)
And it stops running
The same thing goes for the testing as well.

If you guys could help me, I'd be grateful please

PS : I am trying to train pv-rcnn on kitti database

**Comment by udacityyy** [comment]
It seems that adding the --merge_all_iters_to_one_epoch has solved this problem :
I first used :
python train.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml  --batch_size 1 --epochs 80 --workers 0

But now I have used 
python train.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml  --merge_all_iters_to_one_epoch

Could someone explain please what does the :  --merge_all_iters_to_one_epoch do ? I'm kinda new to this
